// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto;

@SuppressWarnings("unused")
public final class FieldType {
  private FieldType() { }
  public static final byte NONE = 0;
  public static final byte FieldString = 1;
  public static final byte FieldBool = 2;
  public static final byte FieldI8 = 3;
  public static final byte FieldI16 = 4;
  public static final byte FieldI32 = 5;
  public static final byte FieldI64 = 6;
  public static final byte FieldU8 = 7;
  public static final byte FieldU16 = 8;
  public static final byte FieldU32 = 9;
  public static final byte FieldU64 = 10;
  public static final byte FieldFloat = 11;
  public static final byte FieldDouble = 12;

  public static final String[] names = { "NONE", "FieldString", "FieldBool", "FieldI8", "FieldI16", "FieldI32", "FieldI64", "FieldU8", "FieldU16", "FieldU32", "FieldU64", "FieldFloat", "FieldDouble", };

  public static String name(int e) { return names[e]; }
}

