// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FieldBool extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_9_23(); }
  public static FieldBool getRootAsFieldBool(ByteBuffer _bb) { return getRootAsFieldBool(_bb, new FieldBool()); }
  public static FieldBool getRootAsFieldBool(ByteBuffer _bb, FieldBool obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FieldBool __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public boolean field() { int o = __offset(4); return o != 0 ? 0!=bb.get(o + bb_pos) : false; }

  public static int createFieldBool(FlatBufferBuilder builder,
      boolean field) {
    builder.startTable(1);
    FieldBool.addField(builder, field);
    return FieldBool.endFieldBool(builder);
  }

  public static void startFieldBool(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addField(FlatBufferBuilder builder, boolean field) { builder.addBoolean(0, field, false); }
  public static int endFieldBool(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FieldBool get(int j) { return get(new FieldBool(), j); }
    public FieldBool get(FieldBool obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public FieldBoolT unpack() {
    FieldBoolT _o = new FieldBoolT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(FieldBoolT _o) {
    boolean _oField = field();
    _o.setField(_oField);
  }
  public static int pack(FlatBufferBuilder builder, FieldBoolT _o) {
    if (_o == null) return 0;
    return createFieldBool(
      builder,
      _o.getField());
  }
}

