// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FieldDouble extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_9_23(); }
  public static FieldDouble getRootAsFieldDouble(ByteBuffer _bb) { return getRootAsFieldDouble(_bb, new FieldDouble()); }
  public static FieldDouble getRootAsFieldDouble(ByteBuffer _bb, FieldDouble obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FieldDouble __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double field() { int o = __offset(4); return o != 0 ? bb.getDouble(o + bb_pos) : 0.0; }

  public static int createFieldDouble(FlatBufferBuilder builder,
      double field) {
    builder.startTable(1);
    FieldDouble.addField(builder, field);
    return FieldDouble.endFieldDouble(builder);
  }

  public static void startFieldDouble(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addField(FlatBufferBuilder builder, double field) { builder.addDouble(0, field, 0.0); }
  public static int endFieldDouble(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FieldDouble get(int j) { return get(new FieldDouble(), j); }
    public FieldDouble get(FieldDouble obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public FieldDoubleT unpack() {
    FieldDoubleT _o = new FieldDoubleT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(FieldDoubleT _o) {
    double _oField = field();
    _o.setField(_oField);
  }
  public static int pack(FlatBufferBuilder builder, FieldDoubleT _o) {
    if (_o == null) return 0;
    return createFieldDouble(
      builder,
      _o.getField());
  }
}

