// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FieldString extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_9_23(); }
  public static FieldString getRootAsFieldString(ByteBuffer _bb) { return getRootAsFieldString(_bb, new FieldString()); }
  public static FieldString getRootAsFieldString(ByteBuffer _bb, FieldString obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FieldString __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String field() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer fieldAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer fieldInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }

  public static int createFieldString(FlatBufferBuilder builder,
      int fieldOffset) {
    builder.startTable(1);
    FieldString.addField(builder, fieldOffset);
    return FieldString.endFieldString(builder);
  }

  public static void startFieldString(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addField(FlatBufferBuilder builder, int fieldOffset) { builder.addOffset(0, fieldOffset, 0); }
  public static int endFieldString(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FieldString get(int j) { return get(new FieldString(), j); }
    public FieldString get(FieldString obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public FieldStringT unpack() {
    FieldStringT _o = new FieldStringT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(FieldStringT _o) {
    String _oField = field();
    _o.setField(_oField);
  }
  public static int pack(FlatBufferBuilder builder, FieldStringT _o) {
    if (_o == null) return 0;
    int _field = _o.getField() == null ? 0 : builder.createString(_o.getField());
    return createFieldString(
      builder,
      _field);
  }
}

