// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FieldU8 extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_9_23(); }
  public static FieldU8 getRootAsFieldU8(ByteBuffer _bb) { return getRootAsFieldU8(_bb, new FieldU8()); }
  public static FieldU8 getRootAsFieldU8(ByteBuffer _bb, FieldU8 obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FieldU8 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int field() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createFieldU8(FlatBufferBuilder builder,
      int field) {
    builder.startTable(1);
    FieldU8.addField(builder, field);
    return FieldU8.endFieldU8(builder);
  }

  public static void startFieldU8(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addField(FlatBufferBuilder builder, int field) { builder.addByte(0, (byte) field, (byte) 0); }
  public static int endFieldU8(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FieldU8 get(int j) { return get(new FieldU8(), j); }
    public FieldU8 get(FieldU8 obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public FieldU8T unpack() {
    FieldU8T _o = new FieldU8T();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(FieldU8T _o) {
    int _oField = field();
    _o.setField(_oField);
  }
  public static int pack(FlatBufferBuilder builder, FieldU8T _o) {
    if (_o == null) return 0;
    return createFieldU8(
      builder,
      _o.getField());
  }
}

