// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FieldU16 extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_9_23(); }
  public static FieldU16 getRootAsFieldU16(ByteBuffer _bb) { return getRootAsFieldU16(_bb, new FieldU16()); }
  public static FieldU16 getRootAsFieldU16(ByteBuffer _bb, FieldU16 obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FieldU16 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int field() { int o = __offset(4); return o != 0 ? bb.getShort(o + bb_pos) & 0xFFFF : 0; }

  public static int createFieldU16(FlatBufferBuilder builder,
      int field) {
    builder.startTable(1);
    FieldU16.addField(builder, field);
    return FieldU16.endFieldU16(builder);
  }

  public static void startFieldU16(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addField(FlatBufferBuilder builder, int field) { builder.addShort(0, (short) field, (short) 0); }
  public static int endFieldU16(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FieldU16 get(int j) { return get(new FieldU16(), j); }
    public FieldU16 get(FieldU16 obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public FieldU16T unpack() {
    FieldU16T _o = new FieldU16T();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(FieldU16T _o) {
    int _oField = field();
    _o.setField(_oField);
  }
  public static int pack(FlatBufferBuilder builder, FieldU16T _o) {
    if (_o == null) return 0;
    return createFieldU16(
      builder,
      _o.getField());
  }
}

