// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class FieldU32 extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_9_23(); }
  public static FieldU32 getRootAsFieldU32(ByteBuffer _bb) { return getRootAsFieldU32(_bb, new FieldU32()); }
  public static FieldU32 getRootAsFieldU32(ByteBuffer _bb, FieldU32 obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public FieldU32 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long field() { int o = __offset(4); return o != 0 ? (long)bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L; }

  public static int createFieldU32(FlatBufferBuilder builder,
      long field) {
    builder.startTable(1);
    FieldU32.addField(builder, field);
    return FieldU32.endFieldU32(builder);
  }

  public static void startFieldU32(FlatBufferBuilder builder) { builder.startTable(1); }
  public static void addField(FlatBufferBuilder builder, long field) { builder.addInt(0, (int) field, (int) 0L); }
  public static int endFieldU32(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public FieldU32 get(int j) { return get(new FieldU32(), j); }
    public FieldU32 get(FieldU32 obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public FieldU32T unpack() {
    FieldU32T _o = new FieldU32T();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(FieldU32T _o) {
    long _oField = field();
    _o.setField(_oField);
  }
  public static int pack(FlatBufferBuilder builder, FieldU32T _o) {
    if (_o == null) return 0;
    return createFieldU32(
      builder,
      _o.getField());
  }
}

