// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto;

@SuppressWarnings("unused")
public final class SubOperationType {
  private SubOperationType() { }
  public static final byte SPI_WRITE_U8 = 0;
  public static final byte SPI_READ_U8 = 1;
  public static final byte SPI_READ_U16 = 2;
  public static final byte SPI_READ_N = 3;
  public static final byte I2C_READ_U8 = 4;
  public static final byte I2C_WRITE_U8 = 5;

  public static final String[] names = { "SPI_WRITE_U8", "SPI_READ_U8", "SPI_READ_U16", "SPI_READ_N", "I2C_READ_U8", "I2C_WRITE_U8", };

  public static String name(int e) { return names[e]; }
}

