// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class ValueT {
  private String name;
  private byte valtype;
  private String value;

  public String getName() { return name; }

  public void setName(String name) { this.name = name; }

  public byte getValtype() { return valtype; }

  public void setValtype(byte valtype) { this.valtype = valtype; }

  public String getValue() { return value; }

  public void setValue(String value) { this.value = value; }


  public ValueT() {
    this.name = null;
    this.valtype = 0;
    this.value = null;
  }
}

