// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

public class OperationT {
  private String name;
  private byte opType;
  private byte subOpType;
  private Firmoto.ValueT[] args;
  private Firmoto.ValueT[] retval;

  public String getName() { return name; }

  public void setName(String name) { this.name = name; }

  public byte getOpType() { return opType; }

  public void setOpType(byte opType) { this.opType = opType; }

  public byte getSubOpType() { return subOpType; }

  public void setSubOpType(byte subOpType) { this.subOpType = subOpType; }

  public Firmoto.ValueT[] getArgs() { return args; }

  public void setArgs(Firmoto.ValueT[] args) { this.args = args; }

  public Firmoto.ValueT[] getRetval() { return retval; }

  public void setRetval(Firmoto.ValueT[] retval) { this.retval = retval; }


  public OperationT() {
    this.name = null;
    this.opType = 0;
    this.subOpType = 0;
    this.args = null;
    this.retval = null;
  }
  public static OperationT deserializeFromBinary(byte[] fbBuffer) {
    return Operation.getRootAsOperation(ByteBuffer.wrap(fbBuffer)).unpack();
  }
  public byte[] serializeToBinary() {
    FlatBufferBuilder fbb = new FlatBufferBuilder();
    Operation.finishOperationBuffer(fbb, Operation.pack(fbb, this));
    return fbb.sizedByteArray();
  }
}

