// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Operation extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_9_23(); }
  public static Operation getRootAsOperation(ByteBuffer _bb) { return getRootAsOperation(_bb, new Operation()); }
  public static Operation getRootAsOperation(ByteBuffer _bb, Operation obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Operation __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public byte opType() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public byte subOpType() { int o = __offset(8); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public Firmoto.Value args(int j) { return args(new Firmoto.Value(), j); }
  public Firmoto.Value args(Firmoto.Value obj, int j) { int o = __offset(10); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int argsLength() { int o = __offset(10); return o != 0 ? __vector_len(o) : 0; }
  public Firmoto.Value.Vector argsVector() { return argsVector(new Firmoto.Value.Vector()); }
  public Firmoto.Value.Vector argsVector(Firmoto.Value.Vector obj) { int o = __offset(10); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }
  public Firmoto.Value retval(int j) { return retval(new Firmoto.Value(), j); }
  public Firmoto.Value retval(Firmoto.Value obj, int j) { int o = __offset(12); return o != 0 ? obj.__assign(__indirect(__vector(o) + j * 4), bb) : null; }
  public int retvalLength() { int o = __offset(12); return o != 0 ? __vector_len(o) : 0; }
  public Firmoto.Value.Vector retvalVector() { return retvalVector(new Firmoto.Value.Vector()); }
  public Firmoto.Value.Vector retvalVector(Firmoto.Value.Vector obj) { int o = __offset(12); return o != 0 ? obj.__assign(__vector(o), 4, bb) : null; }

  public static int createOperation(FlatBufferBuilder builder,
      int nameOffset,
      byte opType,
      byte subOpType,
      int argsOffset,
      int retvalOffset) {
    builder.startTable(5);
    Operation.addRetval(builder, retvalOffset);
    Operation.addArgs(builder, argsOffset);
    Operation.addName(builder, nameOffset);
    Operation.addSubOpType(builder, subOpType);
    Operation.addOpType(builder, opType);
    return Operation.endOperation(builder);
  }

  public static void startOperation(FlatBufferBuilder builder) { builder.startTable(5); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addOpType(FlatBufferBuilder builder, byte opType) { builder.addByte(1, opType, 0); }
  public static void addSubOpType(FlatBufferBuilder builder, byte subOpType) { builder.addByte(2, subOpType, 0); }
  public static void addArgs(FlatBufferBuilder builder, int argsOffset) { builder.addOffset(3, argsOffset, 0); }
  public static int createArgsVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startArgsVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static void addRetval(FlatBufferBuilder builder, int retvalOffset) { builder.addOffset(4, retvalOffset, 0); }
  public static int createRetvalVector(FlatBufferBuilder builder, int[] data) { builder.startVector(4, data.length, 4); for (int i = data.length - 1; i >= 0; i--) builder.addOffset(data[i]); return builder.endVector(); }
  public static void startRetvalVector(FlatBufferBuilder builder, int numElems) { builder.startVector(4, numElems, 4); }
  public static int endOperation(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }
  public static void finishOperationBuffer(FlatBufferBuilder builder, int offset) { builder.finish(offset); }
  public static void finishSizePrefixedOperationBuffer(FlatBufferBuilder builder, int offset) { builder.finishSizePrefixed(offset); }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Operation get(int j) { return get(new Operation(), j); }
    public Operation get(Operation obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

