// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class Value extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_25_9_23(); }
  public static Value getRootAsValue(ByteBuffer _bb) { return getRootAsValue(_bb, new Value()); }
  public static Value getRootAsValue(ByteBuffer _bb, Value obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public Value __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String name() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer nameAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer nameInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public byte valtype() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public String value() { int o = __offset(8); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer valueAsByteBuffer() { return __vector_as_bytebuffer(8, 1); }
  public ByteBuffer valueInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 8, 1); }

  public static int createValue(FlatBufferBuilder builder,
      int nameOffset,
      byte valtype,
      int valueOffset) {
    builder.startTable(3);
    Value.addValue(builder, valueOffset);
    Value.addName(builder, nameOffset);
    Value.addValtype(builder, valtype);
    return Value.endValue(builder);
  }

  public static void startValue(FlatBufferBuilder builder) { builder.startTable(3); }
  public static void addName(FlatBufferBuilder builder, int nameOffset) { builder.addOffset(0, nameOffset, 0); }
  public static void addValtype(FlatBufferBuilder builder, byte valtype) { builder.addByte(1, valtype, 0); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(2, valueOffset, 0); }
  public static int endValue(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public Value get(int j) { return get(new Value(), j); }
    public Value get(Value obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public ValueT unpack() {
    ValueT _o = new ValueT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(ValueT _o) {
    String _oName = name();
    _o.setName(_oName);
    byte _oValtype = valtype();
    _o.setValtype(_oValtype);
    String _oValue = value();
    _o.setValue(_oValue);
  }
  public static int pack(FlatBufferBuilder builder, ValueT _o) {
    if (_o == null) return 0;
    int _name = _o.getName() == null ? 0 : builder.createString(_o.getName());
    int _value = _o.getValue() == null ? 0 : builder.createString(_o.getValue());
    return createValue(
      builder,
      _name,
      _o.getValtype(),
      _value);
  }
}

