// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto;

@SuppressWarnings("unused")
public final class ValueType {
  private ValueType() { }
  public static final byte U8 = 0;
  public static final byte U16 = 1;
  public static final byte U32 = 2;
  public static final byte U64 = 3;
  public static final byte I8 = 4;
  public static final byte I16 = 5;
  public static final byte I32 = 6;
  public static final byte I64 = 7;
  public static final byte F32 = 8;
  public static final byte F64 = 9;
  public static final byte String = 10;
  public static final byte Boolean = 11;

  public static final String[] names = { "U8", "U16", "U32", "U64", "I8", "I16", "I32", "I64", "F32", "F64", "String", "Boolean", };

  public static String name(int e) { return names[e]; }
}

