// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class FieldU64 : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : FieldU64 {
        __init(_i, _bb)
        return this
    }
    val field : ULong
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos).toULong() else 0UL
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsFieldU64(_bb: ByteBuffer): FieldU64 = getRootAsFieldU64(_bb, FieldU64())
        fun getRootAsFieldU64(_bb: ByteBuffer, obj: FieldU64): FieldU64 {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createFieldU64(builder: FlatBufferBuilder, field: ULong) : Int {
            builder.startTable(1)
            addField(builder, field)
            return endFieldU64(builder)
        }
        fun startFieldU64(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addField(builder: FlatBufferBuilder, field: ULong) = builder.addLong(0, field.toLong(), 0)
        fun endFieldU64(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
