// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class FieldU16 : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : FieldU16 {
        __init(_i, _bb)
        return this
    }
    val field : UShort
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getShort(o + bb_pos).toUShort() else 0u
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsFieldU16(_bb: ByteBuffer): FieldU16 = getRootAsFieldU16(_bb, FieldU16())
        fun getRootAsFieldU16(_bb: ByteBuffer, obj: FieldU16): FieldU16 {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createFieldU16(builder: FlatBufferBuilder, field: UShort) : Int {
            builder.startTable(1)
            addField(builder, field)
            return endFieldU16(builder)
        }
        fun startFieldU16(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addField(builder: FlatBufferBuilder, field: UShort) = builder.addShort(0, field.toShort(), 0)
        fun endFieldU16(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
