// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class FieldU32 : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : FieldU32 {
        __init(_i, _bb)
        return this
    }
    val field : UInt
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos).toUInt() else 0u
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsFieldU32(_bb: ByteBuffer): FieldU32 = getRootAsFieldU32(_bb, FieldU32())
        fun getRootAsFieldU32(_bb: ByteBuffer, obj: FieldU32): FieldU32 {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createFieldU32(builder: FlatBufferBuilder, field: UInt) : Int {
            builder.startTable(1)
            addField(builder, field)
            return endFieldU32(builder)
        }
        fun startFieldU32(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addField(builder: FlatBufferBuilder, field: UInt) = builder.addInt(0, field.toInt(), 0)
        fun endFieldU32(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
