// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class FieldString : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : FieldString {
        __init(_i, _bb)
        return this
    }
    val field : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val fieldAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun fieldInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsFieldString(_bb: ByteBuffer): FieldString = getRootAsFieldString(_bb, FieldString())
        fun getRootAsFieldString(_bb: ByteBuffer, obj: FieldString): FieldString {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createFieldString(builder: FlatBufferBuilder, fieldOffset: Int) : Int {
            builder.startTable(1)
            addField(builder, fieldOffset)
            return endFieldString(builder)
        }
        fun startFieldString(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addField(builder: FlatBufferBuilder, field: Int) = builder.addOffset(0, field, 0)
        fun endFieldString(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
