// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class FieldDouble : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : FieldDouble {
        __init(_i, _bb)
        return this
    }
    val field : Double
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getDouble(o + bb_pos) else 0.0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsFieldDouble(_bb: ByteBuffer): FieldDouble = getRootAsFieldDouble(_bb, FieldDouble())
        fun getRootAsFieldDouble(_bb: ByteBuffer, obj: FieldDouble): FieldDouble {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createFieldDouble(builder: FlatBufferBuilder, field: Double) : Int {
            builder.startTable(1)
            addField(builder, field)
            return endFieldDouble(builder)
        }
        fun startFieldDouble(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addField(builder: FlatBufferBuilder, field: Double) = builder.addDouble(0, field, 0.0)
        fun endFieldDouble(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
