// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class FieldI8 : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : FieldI8 {
        __init(_i, _bb)
        return this
    }
    val field : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsFieldI8(_bb: ByteBuffer): FieldI8 = getRootAsFieldI8(_bb, FieldI8())
        fun getRootAsFieldI8(_bb: ByteBuffer, obj: FieldI8): FieldI8 {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createFieldI8(builder: FlatBufferBuilder, field: Byte) : Int {
            builder.startTable(1)
            addField(builder, field)
            return endFieldI8(builder)
        }
        fun startFieldI8(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addField(builder: FlatBufferBuilder, field: Byte) = builder.addByte(0, field, 0)
        fun endFieldI8(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
