// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class Operation : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : Operation {
        __init(_i, _bb)
        return this
    }
    val name : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val nameAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun nameInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val opType : Byte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val subOpType : Byte
        get() {
            val o = __offset(8)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    fun args(j: Int) : Firmoto.Value? = args(Firmoto.Value(), j)
    fun args(obj: Firmoto.Value, j: Int) : Firmoto.Value? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val argsLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    fun retval(j: Int) : Firmoto.Value? = retval(Firmoto.Value(), j)
    fun retval(obj: Firmoto.Value, j: Int) : Firmoto.Value? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val retvalLength : Int
        get() {
            val o = __offset(12); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_25_9_23()
        fun getRootAsOperation(_bb: ByteBuffer): Operation = getRootAsOperation(_bb, Operation())
        fun getRootAsOperation(_bb: ByteBuffer, obj: Operation): Operation {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createOperation(builder: FlatBufferBuilder, nameOffset: Int, opType: Byte, subOpType: Byte, argsOffset: Int, retvalOffset: Int) : Int {
            builder.startTable(5)
            addRetval(builder, retvalOffset)
            addArgs(builder, argsOffset)
            addName(builder, nameOffset)
            addSubOpType(builder, subOpType)
            addOpType(builder, opType)
            return endOperation(builder)
        }
        fun startOperation(builder: FlatBufferBuilder) = builder.startTable(5)
        fun addName(builder: FlatBufferBuilder, name: Int) = builder.addOffset(0, name, 0)
        fun addOpType(builder: FlatBufferBuilder, opType: Byte) = builder.addByte(1, opType, 0)
        fun addSubOpType(builder: FlatBufferBuilder, subOpType: Byte) = builder.addByte(2, subOpType, 0)
        fun addArgs(builder: FlatBufferBuilder, args: Int) = builder.addOffset(3, args, 0)
        fun createArgsVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startArgsVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addRetval(builder: FlatBufferBuilder, retval: Int) = builder.addOffset(4, retval, 0)
        fun createRetvalVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startRetvalVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endOperation(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
        fun finishOperationBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finish(offset)
        fun finishSizePrefixedOperationBuffer(builder: FlatBufferBuilder, offset: Int) = builder.finishSizePrefixed(offset)
    }
}
