// automatically generated by the FlatBuffers compiler, do not modify

package Firmoto

@Suppress("unused")
class OperationType private constructor() {
    companion object {
        const val GPIO: Byte = 0
        const val I2C: Byte = 1
        const val SPI: Byte = 2
    }
}
