// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Firmoto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FieldBool : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static FieldBool GetRootAsFieldBool(ByteBuffer _bb) { return GetRootAsFieldBool(_bb, new FieldBool()); }
  public static FieldBool GetRootAsFieldBool(ByteBuffer _bb, FieldBool obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FieldBool __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Field { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<Firmoto.FieldBool> CreateFieldBool(FlatBufferBuilder builder,
      bool field = false) {
    builder.StartTable(1);
    FieldBool.AddField(builder, field);
    return FieldBool.EndFieldBool(builder);
  }

  public static void StartFieldBool(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddField(FlatBufferBuilder builder, bool field) { builder.AddBool(0, field, false); }
  public static Offset<Firmoto.FieldBool> EndFieldBool(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Firmoto.FieldBool>(o);
  }
  public FieldBoolT UnPack() {
    var _o = new FieldBoolT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(FieldBoolT _o) {
    _o.Field = this.Field;
  }
  public static Offset<Firmoto.FieldBool> Pack(FlatBufferBuilder builder, FieldBoolT _o) {
    if (_o == null) return default(Offset<Firmoto.FieldBool>);
    return CreateFieldBool(
      builder,
      _o.Field);
  }
}

public class FieldBoolT
{
  public bool Field { get; set; }

  public FieldBoolT() {
    this.Field = false;
  }
}


static public class FieldBoolVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Field*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
