// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Firmoto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FieldU64 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static FieldU64 GetRootAsFieldU64(ByteBuffer _bb) { return GetRootAsFieldU64(_bb, new FieldU64()); }
  public static FieldU64 GetRootAsFieldU64(ByteBuffer _bb, FieldU64 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FieldU64 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Field { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<Firmoto.FieldU64> CreateFieldU64(FlatBufferBuilder builder,
      ulong field = 0) {
    builder.StartTable(1);
    FieldU64.AddField(builder, field);
    return FieldU64.EndFieldU64(builder);
  }

  public static void StartFieldU64(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddField(FlatBufferBuilder builder, ulong field) { builder.AddUlong(0, field, 0); }
  public static Offset<Firmoto.FieldU64> EndFieldU64(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Firmoto.FieldU64>(o);
  }
  public FieldU64T UnPack() {
    var _o = new FieldU64T();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(FieldU64T _o) {
    _o.Field = this.Field;
  }
  public static Offset<Firmoto.FieldU64> Pack(FlatBufferBuilder builder, FieldU64T _o) {
    if (_o == null) return default(Offset<Firmoto.FieldU64>);
    return CreateFieldU64(
      builder,
      _o.Field);
  }
}

public class FieldU64T
{
  public ulong Field { get; set; }

  public FieldU64T() {
    this.Field = 0;
  }
}


static public class FieldU64Verify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Field*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
