// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Firmoto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FieldI64 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static FieldI64 GetRootAsFieldI64(ByteBuffer _bb) { return GetRootAsFieldI64(_bb, new FieldI64()); }
  public static FieldI64 GetRootAsFieldI64(ByteBuffer _bb, FieldI64 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FieldI64 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public long Field { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetLong(o + __p.bb_pos) : (long)0; } }

  public static Offset<Firmoto.FieldI64> CreateFieldI64(FlatBufferBuilder builder,
      long field = 0) {
    builder.StartTable(1);
    FieldI64.AddField(builder, field);
    return FieldI64.EndFieldI64(builder);
  }

  public static void StartFieldI64(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddField(FlatBufferBuilder builder, long field) { builder.AddLong(0, field, 0); }
  public static Offset<Firmoto.FieldI64> EndFieldI64(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Firmoto.FieldI64>(o);
  }
  public FieldI64T UnPack() {
    var _o = new FieldI64T();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(FieldI64T _o) {
    _o.Field = this.Field;
  }
  public static Offset<Firmoto.FieldI64> Pack(FlatBufferBuilder builder, FieldI64T _o) {
    if (_o == null) return default(Offset<Firmoto.FieldI64>);
    return CreateFieldI64(
      builder,
      _o.Field);
  }
}

public class FieldI64T
{
  public long Field { get; set; }

  public FieldI64T() {
    this.Field = 0;
  }
}


static public class FieldI64Verify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Field*/, 8 /*long*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
