// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Firmoto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FieldDouble : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static FieldDouble GetRootAsFieldDouble(ByteBuffer _bb) { return GetRootAsFieldDouble(_bb, new FieldDouble()); }
  public static FieldDouble GetRootAsFieldDouble(ByteBuffer _bb, FieldDouble obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FieldDouble __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public double Field { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetDouble(o + __p.bb_pos) : (double)0.0; } }

  public static Offset<Firmoto.FieldDouble> CreateFieldDouble(FlatBufferBuilder builder,
      double field = 0.0) {
    builder.StartTable(1);
    FieldDouble.AddField(builder, field);
    return FieldDouble.EndFieldDouble(builder);
  }

  public static void StartFieldDouble(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddField(FlatBufferBuilder builder, double field) { builder.AddDouble(0, field, 0.0); }
  public static Offset<Firmoto.FieldDouble> EndFieldDouble(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Firmoto.FieldDouble>(o);
  }
  public FieldDoubleT UnPack() {
    var _o = new FieldDoubleT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(FieldDoubleT _o) {
    _o.Field = this.Field;
  }
  public static Offset<Firmoto.FieldDouble> Pack(FlatBufferBuilder builder, FieldDoubleT _o) {
    if (_o == null) return default(Offset<Firmoto.FieldDouble>);
    return CreateFieldDouble(
      builder,
      _o.Field);
  }
}

public class FieldDoubleT
{
  public double Field { get; set; }

  public FieldDoubleT() {
    this.Field = 0.0;
  }
}


static public class FieldDoubleVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Field*/, 8 /*double*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
