// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Firmoto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FieldString : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static FieldString GetRootAsFieldString(ByteBuffer _bb) { return GetRootAsFieldString(_bb, new FieldString()); }
  public static FieldString GetRootAsFieldString(ByteBuffer _bb, FieldString obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FieldString __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Field { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetFieldBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetFieldBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetFieldArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<Firmoto.FieldString> CreateFieldString(FlatBufferBuilder builder,
      StringOffset fieldOffset = default(StringOffset)) {
    builder.StartTable(1);
    FieldString.AddField(builder, fieldOffset);
    return FieldString.EndFieldString(builder);
  }

  public static void StartFieldString(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddField(FlatBufferBuilder builder, StringOffset fieldOffset) { builder.AddOffset(0, fieldOffset.Value, 0); }
  public static Offset<Firmoto.FieldString> EndFieldString(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Firmoto.FieldString>(o);
  }
  public FieldStringT UnPack() {
    var _o = new FieldStringT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(FieldStringT _o) {
    _o.Field = this.Field;
  }
  public static Offset<Firmoto.FieldString> Pack(FlatBufferBuilder builder, FieldStringT _o) {
    if (_o == null) return default(Offset<Firmoto.FieldString>);
    var _field = _o.Field == null ? default(StringOffset) : builder.CreateString(_o.Field);
    return CreateFieldString(
      builder,
      _field);
  }
}

public class FieldStringT
{
  public string Field { get; set; }

  public FieldStringT() {
    this.Field = null;
  }
}


static public class FieldStringVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Field*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
