// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Firmoto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FieldFloat : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static FieldFloat GetRootAsFieldFloat(ByteBuffer _bb) { return GetRootAsFieldFloat(_bb, new FieldFloat()); }
  public static FieldFloat GetRootAsFieldFloat(ByteBuffer _bb, FieldFloat obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FieldFloat __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Field { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<Firmoto.FieldFloat> CreateFieldFloat(FlatBufferBuilder builder,
      float field = 0.0f) {
    builder.StartTable(1);
    FieldFloat.AddField(builder, field);
    return FieldFloat.EndFieldFloat(builder);
  }

  public static void StartFieldFloat(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddField(FlatBufferBuilder builder, float field) { builder.AddFloat(0, field, 0.0f); }
  public static Offset<Firmoto.FieldFloat> EndFieldFloat(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Firmoto.FieldFloat>(o);
  }
  public FieldFloatT UnPack() {
    var _o = new FieldFloatT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(FieldFloatT _o) {
    _o.Field = this.Field;
  }
  public static Offset<Firmoto.FieldFloat> Pack(FlatBufferBuilder builder, FieldFloatT _o) {
    if (_o == null) return default(Offset<Firmoto.FieldFloat>);
    return CreateFieldFloat(
      builder,
      _o.Field);
  }
}

public class FieldFloatT
{
  public float Field { get; set; }

  public FieldFloatT() {
    this.Field = 0.0f;
  }
}


static public class FieldFloatVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Field*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
