// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Firmoto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FieldU8 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static FieldU8 GetRootAsFieldU8(ByteBuffer _bb) { return GetRootAsFieldU8(_bb, new FieldU8()); }
  public static FieldU8 GetRootAsFieldU8(ByteBuffer _bb, FieldU8 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FieldU8 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte Field { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<Firmoto.FieldU8> CreateFieldU8(FlatBufferBuilder builder,
      byte field = 0) {
    builder.StartTable(1);
    FieldU8.AddField(builder, field);
    return FieldU8.EndFieldU8(builder);
  }

  public static void StartFieldU8(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddField(FlatBufferBuilder builder, byte field) { builder.AddByte(0, field, 0); }
  public static Offset<Firmoto.FieldU8> EndFieldU8(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Firmoto.FieldU8>(o);
  }
  public FieldU8T UnPack() {
    var _o = new FieldU8T();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(FieldU8T _o) {
    _o.Field = this.Field;
  }
  public static Offset<Firmoto.FieldU8> Pack(FlatBufferBuilder builder, FieldU8T _o) {
    if (_o == null) return default(Offset<Firmoto.FieldU8>);
    return CreateFieldU8(
      builder,
      _o.Field);
  }
}

public class FieldU8T
{
  public byte Field { get; set; }

  public FieldU8T() {
    this.Field = 0;
  }
}


static public class FieldU8Verify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Field*/, 1 /*byte*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
