// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Firmoto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FieldU16 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static FieldU16 GetRootAsFieldU16(ByteBuffer _bb) { return GetRootAsFieldU16(_bb, new FieldU16()); }
  public static FieldU16 GetRootAsFieldU16(ByteBuffer _bb, FieldU16 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FieldU16 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ushort Field { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUshort(o + __p.bb_pos) : (ushort)0; } }

  public static Offset<Firmoto.FieldU16> CreateFieldU16(FlatBufferBuilder builder,
      ushort field = 0) {
    builder.StartTable(1);
    FieldU16.AddField(builder, field);
    return FieldU16.EndFieldU16(builder);
  }

  public static void StartFieldU16(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddField(FlatBufferBuilder builder, ushort field) { builder.AddUshort(0, field, 0); }
  public static Offset<Firmoto.FieldU16> EndFieldU16(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Firmoto.FieldU16>(o);
  }
  public FieldU16T UnPack() {
    var _o = new FieldU16T();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(FieldU16T _o) {
    _o.Field = this.Field;
  }
  public static Offset<Firmoto.FieldU16> Pack(FlatBufferBuilder builder, FieldU16T _o) {
    if (_o == null) return default(Offset<Firmoto.FieldU16>);
    return CreateFieldU16(
      builder,
      _o.Field);
  }
}

public class FieldU16T
{
  public ushort Field { get; set; }

  public FieldU16T() {
    this.Field = 0;
  }
}


static public class FieldU16Verify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Field*/, 2 /*ushort*/, 2, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
