// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Firmoto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FieldU32 : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static FieldU32 GetRootAsFieldU32(ByteBuffer _bb) { return GetRootAsFieldU32(_bb, new FieldU32()); }
  public static FieldU32 GetRootAsFieldU32(ByteBuffer _bb, FieldU32 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FieldU32 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Field { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }

  public static Offset<Firmoto.FieldU32> CreateFieldU32(FlatBufferBuilder builder,
      uint field = 0) {
    builder.StartTable(1);
    FieldU32.AddField(builder, field);
    return FieldU32.EndFieldU32(builder);
  }

  public static void StartFieldU32(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddField(FlatBufferBuilder builder, uint field) { builder.AddUint(0, field, 0); }
  public static Offset<Firmoto.FieldU32> EndFieldU32(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Firmoto.FieldU32>(o);
  }
  public FieldU32T UnPack() {
    var _o = new FieldU32T();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(FieldU32T _o) {
    _o.Field = this.Field;
  }
  public static Offset<Firmoto.FieldU32> Pack(FlatBufferBuilder builder, FieldU32T _o) {
    if (_o == null) return default(Offset<Firmoto.FieldU32>);
    return CreateFieldU32(
      builder,
      _o.Field);
  }
}

public class FieldU32T
{
  public uint Field { get; set; }

  public FieldU32T() {
    this.Field = 0;
  }
}


static public class FieldU32Verify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Field*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
