// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Firmoto
{

public enum OperationType : sbyte
{
  GPIO = 0,
  I2C = 1,
  SPI = 2,
  CAN = 3,
};


}
