// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Firmoto
{

public enum SubOperationType : sbyte
{
  SPI_WRITE_U8 = 0,
  SPI_READ_U8 = 1,
  SPI_READ_U16 = 2,
  SPI_READ_N = 3,
};


}
