// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Firmoto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Value : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static Value GetRootAsValue(ByteBuffer _bb) { return GetRootAsValue(_bb, new Value()); }
  public static Value GetRootAsValue(ByteBuffer _bb, Value obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Value __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public Firmoto.ValueType Valtype { get { int o = __p.__offset(6); return o != 0 ? (Firmoto.ValueType)__p.bb.GetSbyte(o + __p.bb_pos) : Firmoto.ValueType.U8; } }
  public string Value_ { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetValueBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetValueBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetValueArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<Firmoto.Value> CreateValue(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      Firmoto.ValueType valtype = Firmoto.ValueType.U8,
      StringOffset valueOffset = default(StringOffset)) {
    builder.StartTable(3);
    Value.AddValue(builder, valueOffset);
    Value.AddName(builder, nameOffset);
    Value.AddValtype(builder, valtype);
    return Value.EndValue(builder);
  }

  public static void StartValue(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddValtype(FlatBufferBuilder builder, Firmoto.ValueType valtype) { builder.AddSbyte(1, (sbyte)valtype, 0); }
  public static void AddValue(FlatBufferBuilder builder, StringOffset valueOffset) { builder.AddOffset(2, valueOffset.Value, 0); }
  public static Offset<Firmoto.Value> EndValue(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Firmoto.Value>(o);
  }
  public ValueT UnPack() {
    var _o = new ValueT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ValueT _o) {
    _o.Name = this.Name;
    _o.Valtype = this.Valtype;
    _o.Value_ = this.Value_;
  }
  public static Offset<Firmoto.Value> Pack(FlatBufferBuilder builder, ValueT _o) {
    if (_o == null) return default(Offset<Firmoto.Value>);
    var _name = _o.Name == null ? default(StringOffset) : builder.CreateString(_o.Name);
    var _value = _o.Value_ == null ? default(StringOffset) : builder.CreateString(_o.Value_);
    return CreateValue(
      builder,
      _name,
      _o.Valtype,
      _value);
  }
}

public class ValueT
{
  public string Name { get; set; }
  public Firmoto.ValueType Valtype { get; set; }
  public string Value_ { get; set; }

  public ValueT() {
    this.Name = null;
    this.Valtype = Firmoto.ValueType.U8;
    this.Value_ = null;
  }
}


static public class ValueVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, false)
      && verifier.VerifyField(tablePos, 6 /*Valtype*/, 1 /*Firmoto.ValueType*/, 1, false)
      && verifier.VerifyString(tablePos, 8 /*Value*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
