// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class FieldI32 implements flatbuffers.IUnpackableObject<FieldI32T> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FieldI32 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFieldI32(bb:flatbuffers.ByteBuffer, obj?:FieldI32):FieldI32 {
  return (obj || new FieldI32()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFieldI32(bb:flatbuffers.ByteBuffer, obj?:FieldI32):FieldI32 {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FieldI32()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

field():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startFieldI32(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addField(builder:flatbuffers.Builder, field:number) {
  builder.addFieldInt32(0, field, 0);
}

static endFieldI32(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFieldI32(builder:flatbuffers.Builder, field:number):flatbuffers.Offset {
  FieldI32.startFieldI32(builder);
  FieldI32.addField(builder, field);
  return FieldI32.endFieldI32(builder);
}

unpack(): FieldI32T {
  return new FieldI32T(
    this.field()
  );
}


unpackTo(_o: FieldI32T): void {
  _o.field = this.field();
}
}

export class FieldI32T implements flatbuffers.IGeneratedObject {
constructor(
  public field: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return FieldI32.createFieldI32(builder,
    this.field
  );
}
}
