// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class FieldFloat implements flatbuffers.IUnpackableObject<FieldFloatT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FieldFloat {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFieldFloat(bb:flatbuffers.ByteBuffer, obj?:FieldFloat):FieldFloat {
  return (obj || new FieldFloat()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFieldFloat(bb:flatbuffers.ByteBuffer, obj?:FieldFloat):FieldFloat {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FieldFloat()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

field():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startFieldFloat(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addField(builder:flatbuffers.Builder, field:number) {
  builder.addFieldFloat32(0, field, 0.0);
}

static endFieldFloat(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFieldFloat(builder:flatbuffers.Builder, field:number):flatbuffers.Offset {
  FieldFloat.startFieldFloat(builder);
  FieldFloat.addField(builder, field);
  return FieldFloat.endFieldFloat(builder);
}

unpack(): FieldFloatT {
  return new FieldFloatT(
    this.field()
  );
}


unpackTo(_o: FieldFloatT): void {
  _o.field = this.field();
}
}

export class FieldFloatT implements flatbuffers.IGeneratedObject {
constructor(
  public field: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return FieldFloat.createFieldFloat(builder,
    this.field
  );
}
}
