// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class FieldBool implements flatbuffers.IUnpackableObject<FieldBoolT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FieldBool {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFieldBool(bb:flatbuffers.ByteBuffer, obj?:FieldBool):FieldBool {
  return (obj || new FieldBool()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFieldBool(bb:flatbuffers.ByteBuffer, obj?:FieldBool):FieldBool {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FieldBool()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

field():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startFieldBool(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addField(builder:flatbuffers.Builder, field:boolean) {
  builder.addFieldInt8(0, +field, +false);
}

static endFieldBool(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFieldBool(builder:flatbuffers.Builder, field:boolean):flatbuffers.Offset {
  FieldBool.startFieldBool(builder);
  FieldBool.addField(builder, field);
  return FieldBool.endFieldBool(builder);
}

unpack(): FieldBoolT {
  return new FieldBoolT(
    this.field()
  );
}


unpackTo(_o: FieldBoolT): void {
  _o.field = this.field();
}
}

export class FieldBoolT implements flatbuffers.IGeneratedObject {
constructor(
  public field: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return FieldBool.createFieldBool(builder,
    this.field
  );
}
}
