// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class FieldU16 implements flatbuffers.IUnpackableObject<FieldU16T> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FieldU16 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFieldU16(bb:flatbuffers.ByteBuffer, obj?:FieldU16):FieldU16 {
  return (obj || new FieldU16()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFieldU16(bb:flatbuffers.ByteBuffer, obj?:FieldU16):FieldU16 {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FieldU16()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

field():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

static startFieldU16(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addField(builder:flatbuffers.Builder, field:number) {
  builder.addFieldInt16(0, field, 0);
}

static endFieldU16(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFieldU16(builder:flatbuffers.Builder, field:number):flatbuffers.Offset {
  FieldU16.startFieldU16(builder);
  FieldU16.addField(builder, field);
  return FieldU16.endFieldU16(builder);
}

unpack(): FieldU16T {
  return new FieldU16T(
    this.field()
  );
}


unpackTo(_o: FieldU16T): void {
  _o.field = this.field();
}
}

export class FieldU16T implements flatbuffers.IGeneratedObject {
constructor(
  public field: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return FieldU16.createFieldU16(builder,
    this.field
  );
}
}
