// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class FieldU32 implements flatbuffers.IUnpackableObject<FieldU32T> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FieldU32 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFieldU32(bb:flatbuffers.ByteBuffer, obj?:FieldU32):FieldU32 {
  return (obj || new FieldU32()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFieldU32(bb:flatbuffers.ByteBuffer, obj?:FieldU32):FieldU32 {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FieldU32()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

field():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

static startFieldU32(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addField(builder:flatbuffers.Builder, field:number) {
  builder.addFieldInt32(0, field, 0);
}

static endFieldU32(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFieldU32(builder:flatbuffers.Builder, field:number):flatbuffers.Offset {
  FieldU32.startFieldU32(builder);
  FieldU32.addField(builder, field);
  return FieldU32.endFieldU32(builder);
}

unpack(): FieldU32T {
  return new FieldU32T(
    this.field()
  );
}


unpackTo(_o: FieldU32T): void {
  _o.field = this.field();
}
}

export class FieldU32T implements flatbuffers.IGeneratedObject {
constructor(
  public field: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return FieldU32.createFieldU32(builder,
    this.field
  );
}
}
