// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class FieldI16 implements flatbuffers.IUnpackableObject<FieldI16T> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FieldI16 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFieldI16(bb:flatbuffers.ByteBuffer, obj?:FieldI16):FieldI16 {
  return (obj || new FieldI16()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFieldI16(bb:flatbuffers.ByteBuffer, obj?:FieldI16):FieldI16 {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FieldI16()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

field():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt16(this.bb_pos + offset) : 0;
}

static startFieldI16(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addField(builder:flatbuffers.Builder, field:number) {
  builder.addFieldInt16(0, field, 0);
}

static endFieldI16(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFieldI16(builder:flatbuffers.Builder, field:number):flatbuffers.Offset {
  FieldI16.startFieldI16(builder);
  FieldI16.addField(builder, field);
  return FieldI16.endFieldI16(builder);
}

unpack(): FieldI16T {
  return new FieldI16T(
    this.field()
  );
}


unpackTo(_o: FieldI16T): void {
  _o.field = this.field();
}
}

export class FieldI16T implements flatbuffers.IGeneratedObject {
constructor(
  public field: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return FieldI16.createFieldI16(builder,
    this.field
  );
}
}
