// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class FieldU64 implements flatbuffers.IUnpackableObject<FieldU64T> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FieldU64 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFieldU64(bb:flatbuffers.ByteBuffer, obj?:FieldU64):FieldU64 {
  return (obj || new FieldU64()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFieldU64(bb:flatbuffers.ByteBuffer, obj?:FieldU64):FieldU64 {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FieldU64()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

field():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startFieldU64(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addField(builder:flatbuffers.Builder, field:bigint) {
  builder.addFieldInt64(0, field, BigInt('0'));
}

static endFieldU64(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFieldU64(builder:flatbuffers.Builder, field:bigint):flatbuffers.Offset {
  FieldU64.startFieldU64(builder);
  FieldU64.addField(builder, field);
  return FieldU64.endFieldU64(builder);
}

unpack(): FieldU64T {
  return new FieldU64T(
    this.field()
  );
}


unpackTo(_o: FieldU64T): void {
  _o.field = this.field();
}
}

export class FieldU64T implements flatbuffers.IGeneratedObject {
constructor(
  public field: bigint = BigInt('0')
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return FieldU64.createFieldU64(builder,
    this.field
  );
}
}
