// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class FieldDouble implements flatbuffers.IUnpackableObject<FieldDoubleT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FieldDouble {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFieldDouble(bb:flatbuffers.ByteBuffer, obj?:FieldDouble):FieldDouble {
  return (obj || new FieldDouble()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFieldDouble(bb:flatbuffers.ByteBuffer, obj?:FieldDouble):FieldDouble {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FieldDouble()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

field():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat64(this.bb_pos + offset) : 0.0;
}

static startFieldDouble(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addField(builder:flatbuffers.Builder, field:number) {
  builder.addFieldFloat64(0, field, 0.0);
}

static endFieldDouble(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFieldDouble(builder:flatbuffers.Builder, field:number):flatbuffers.Offset {
  FieldDouble.startFieldDouble(builder);
  FieldDouble.addField(builder, field);
  return FieldDouble.endFieldDouble(builder);
}

unpack(): FieldDoubleT {
  return new FieldDoubleT(
    this.field()
  );
}


unpackTo(_o: FieldDoubleT): void {
  _o.field = this.field();
}
}

export class FieldDoubleT implements flatbuffers.IGeneratedObject {
constructor(
  public field: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return FieldDouble.createFieldDouble(builder,
    this.field
  );
}
}
