// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class FieldString implements flatbuffers.IUnpackableObject<FieldStringT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FieldString {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFieldString(bb:flatbuffers.ByteBuffer, obj?:FieldString):FieldString {
  return (obj || new FieldString()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFieldString(bb:flatbuffers.ByteBuffer, obj?:FieldString):FieldString {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FieldString()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

field():string|null
field(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
field(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startFieldString(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addField(builder:flatbuffers.Builder, fieldOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, fieldOffset, 0);
}

static endFieldString(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFieldString(builder:flatbuffers.Builder, fieldOffset:flatbuffers.Offset):flatbuffers.Offset {
  FieldString.startFieldString(builder);
  FieldString.addField(builder, fieldOffset);
  return FieldString.endFieldString(builder);
}

unpack(): FieldStringT {
  return new FieldStringT(
    this.field()
  );
}


unpackTo(_o: FieldStringT): void {
  _o.field = this.field();
}
}

export class FieldStringT implements flatbuffers.IGeneratedObject {
constructor(
  public field: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const field = (this.field !== null ? builder.createString(this.field!) : 0);

  return FieldString.createFieldString(builder,
    field
  );
}
}
