// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class FieldI8 implements flatbuffers.IUnpackableObject<FieldI8T> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FieldI8 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFieldI8(bb:flatbuffers.ByteBuffer, obj?:FieldI8):FieldI8 {
  return (obj || new FieldI8()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFieldI8(bb:flatbuffers.ByteBuffer, obj?:FieldI8):FieldI8 {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FieldI8()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

field():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : 0;
}

static startFieldI8(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addField(builder:flatbuffers.Builder, field:number) {
  builder.addFieldInt8(0, field, 0);
}

static endFieldI8(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFieldI8(builder:flatbuffers.Builder, field:number):flatbuffers.Offset {
  FieldI8.startFieldI8(builder);
  FieldI8.addField(builder, field);
  return FieldI8.endFieldI8(builder);
}

unpack(): FieldI8T {
  return new FieldI8T(
    this.field()
  );
}


unpackTo(_o: FieldI8T): void {
  _o.field = this.field();
}
}

export class FieldI8T implements flatbuffers.IGeneratedObject {
constructor(
  public field: number = 0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return FieldI8.createFieldI8(builder,
    this.field
  );
}
}
