// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';



export class FieldI64 implements flatbuffers.IUnpackableObject<FieldI64T> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):FieldI64 {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsFieldI64(bb:flatbuffers.ByteBuffer, obj?:FieldI64):FieldI64 {
  return (obj || new FieldI64()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsFieldI64(bb:flatbuffers.ByteBuffer, obj?:FieldI64):FieldI64 {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new FieldI64()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

field():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt64(this.bb_pos + offset) : BigInt('0');
}

static startFieldI64(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addField(builder:flatbuffers.Builder, field:bigint) {
  builder.addFieldInt64(0, field, BigInt('0'));
}

static endFieldI64(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createFieldI64(builder:flatbuffers.Builder, field:bigint):flatbuffers.Offset {
  FieldI64.startFieldI64(builder);
  FieldI64.addField(builder, field);
  return FieldI64.endFieldI64(builder);
}

unpack(): FieldI64T {
  return new FieldI64T(
    this.field()
  );
}


unpackTo(_o: FieldI64T): void {
  _o.field = this.field();
}
}

export class FieldI64T implements flatbuffers.IGeneratedObject {
constructor(
  public field: bigint = BigInt('0')
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return FieldI64.createFieldI64(builder,
    this.field
  );
}
}
