// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Firmoto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct Operation : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static Operation GetRootAsOperation(ByteBuffer _bb) { return GetRootAsOperation(_bb, new Operation()); }
  public static Operation GetRootAsOperation(ByteBuffer _bb, Operation obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyOperation(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, OperationVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Operation __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public Firmoto.OperationType Optype { get { int o = __p.__offset(6); return o != 0 ? (Firmoto.OperationType)__p.bb.GetSbyte(o + __p.bb_pos) : Firmoto.OperationType.GPIO; } }
  public Firmoto.Value? Args(int j) { int o = __p.__offset(8); return o != 0 ? (Firmoto.Value?)(new Firmoto.Value()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ArgsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public Firmoto.Value? Reval(int j) { int o = __p.__offset(10); return o != 0 ? (Firmoto.Value?)(new Firmoto.Value()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int RevalLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Firmoto.Operation> CreateOperation(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      Firmoto.OperationType optype = Firmoto.OperationType.GPIO,
      VectorOffset argsOffset = default(VectorOffset),
      VectorOffset revalOffset = default(VectorOffset)) {
    builder.StartTable(4);
    Operation.AddReval(builder, revalOffset);
    Operation.AddArgs(builder, argsOffset);
    Operation.AddName(builder, nameOffset);
    Operation.AddOptype(builder, optype);
    return Operation.EndOperation(builder);
  }

  public static void StartOperation(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddOptype(FlatBufferBuilder builder, Firmoto.OperationType optype) { builder.AddSbyte(1, (sbyte)optype, 0); }
  public static void AddArgs(FlatBufferBuilder builder, VectorOffset argsOffset) { builder.AddOffset(2, argsOffset.Value, 0); }
  public static VectorOffset CreateArgsVector(FlatBufferBuilder builder, Offset<Firmoto.Value>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateArgsVectorBlock(FlatBufferBuilder builder, Offset<Firmoto.Value>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateArgsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Firmoto.Value>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateArgsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Firmoto.Value>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartArgsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddReval(FlatBufferBuilder builder, VectorOffset revalOffset) { builder.AddOffset(3, revalOffset.Value, 0); }
  public static VectorOffset CreateRevalVector(FlatBufferBuilder builder, Offset<Firmoto.Value>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateRevalVectorBlock(FlatBufferBuilder builder, Offset<Firmoto.Value>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRevalVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Firmoto.Value>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateRevalVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Firmoto.Value>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartRevalVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Firmoto.Operation> EndOperation(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Firmoto.Operation>(o);
  }
  public static void FinishOperationBuffer(FlatBufferBuilder builder, Offset<Firmoto.Operation> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedOperationBuffer(FlatBufferBuilder builder, Offset<Firmoto.Operation> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class OperationVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, false)
      && verifier.VerifyField(tablePos, 6 /*Optype*/, 1 /*Firmoto.OperationType*/, 1, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Args*/, Firmoto.ValueVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 10 /*Reval*/, Firmoto.ValueVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
