// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Firmoto
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct ReturnValue : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_9_23(); }
  public static ReturnValue GetRootAsReturnValue(ByteBuffer _bb) { return GetRootAsReturnValue(_bb, new ReturnValue()); }
  public static ReturnValue GetRootAsReturnValue(ByteBuffer _bb, ReturnValue obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ReturnValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Firmoto.Value? Data(int j) { int o = __p.__offset(4); return o != 0 ? (Firmoto.Value?)(new Firmoto.Value()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DataLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Firmoto.ReturnValue> CreateReturnValue(FlatBufferBuilder builder,
      VectorOffset dataOffset = default(VectorOffset)) {
    builder.StartTable(1);
    ReturnValue.AddData(builder, dataOffset);
    return ReturnValue.EndReturnValue(builder);
  }

  public static void StartReturnValue(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(0, dataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, Offset<Firmoto.Value>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, Offset<Firmoto.Value>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<Firmoto.Value>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<Firmoto.Value>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Firmoto.ReturnValue> EndReturnValue(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<Firmoto.ReturnValue>(o);
  }
  public ReturnValueT UnPack() {
    var _o = new ReturnValueT();
    this.UnPackTo(_o);
    return _o;
  }
  public void UnPackTo(ReturnValueT _o) {
    _o.Data = new List<Firmoto.ValueT>();
    for (var _j = 0; _j < this.DataLength; ++_j) {_o.Data.Add(this.Data(_j).HasValue ? this.Data(_j).Value.UnPack() : null);}
  }
  public static Offset<Firmoto.ReturnValue> Pack(FlatBufferBuilder builder, ReturnValueT _o) {
    if (_o == null) return default(Offset<Firmoto.ReturnValue>);
    var _data = default(VectorOffset);
    if (_o.Data != null) {
      var __data = new Offset<Firmoto.Value>[_o.Data.Count];
      for (var _j = 0; _j < __data.Length; ++_j) { __data[_j] = Firmoto.Value.Pack(builder, _o.Data[_j]); }
      _data = CreateDataVector(builder, __data);
    }
    return CreateReturnValue(
      builder,
      _data);
  }
}

public class ReturnValueT
{
  public List<Firmoto.ValueT> Data { get; set; }

  public ReturnValueT() {
    this.Data = null;
  }
}


static public class ReturnValueVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Data*/, Firmoto.ValueVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
