// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Firmoto
{

public enum ValueType : sbyte
{
  U8 = 0,
  U16 = 1,
  U32 = 2,
  U64 = 3,
  I8 = 4,
  I16 = 5,
  I32 = 6,
  I64 = 7,
  F32 = 8,
  F64 = 9,
  String = 10,
  Boolean = 11,
};


}
