// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FIRMOTOSCHEMA_FIRMOTO_H_
#define FLATBUFFERS_GENERATED_FIRMOTOSCHEMA_FIRMOTO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace Firmoto {

struct Operation;
struct OperationBuilder;

struct Value;
struct ValueBuilder;

enum OperationType : int8_t {
  OperationType_GPIO = 0,
  OperationType_I2C = 1,
  OperationType_SPI = 2,
  OperationType_MIN = OperationType_GPIO,
  OperationType_MAX = OperationType_SPI
};

inline const OperationType (&EnumValuesOperationType())[3] {
  static const OperationType values[] = {
    OperationType_GPIO,
    OperationType_I2C,
    OperationType_SPI
  };
  return values;
}

inline const char * const *EnumNamesOperationType() {
  static const char * const names[4] = {
    "GPIO",
    "I2C",
    "SPI",
    nullptr
  };
  return names;
}

inline const char *EnumNameOperationType(OperationType e) {
  if (::flatbuffers::IsOutRange(e, OperationType_GPIO, OperationType_SPI)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesOperationType()[index];
}

enum ValueType : int8_t {
  ValueType_U8 = 0,
  ValueType_U16 = 1,
  ValueType_U32 = 2,
  ValueType_U64 = 3,
  ValueType_I8 = 4,
  ValueType_I16 = 5,
  ValueType_I32 = 6,
  ValueType_I64 = 7,
  ValueType_F32 = 8,
  ValueType_F64 = 9,
  ValueType_String = 10,
  ValueType_Boolean = 11,
  ValueType_MIN = ValueType_U8,
  ValueType_MAX = ValueType_Boolean
};

inline const ValueType (&EnumValuesValueType())[12] {
  static const ValueType values[] = {
    ValueType_U8,
    ValueType_U16,
    ValueType_U32,
    ValueType_U64,
    ValueType_I8,
    ValueType_I16,
    ValueType_I32,
    ValueType_I64,
    ValueType_F32,
    ValueType_F64,
    ValueType_String,
    ValueType_Boolean
  };
  return values;
}

inline const char * const *EnumNamesValueType() {
  static const char * const names[13] = {
    "U8",
    "U16",
    "U32",
    "U64",
    "I8",
    "I16",
    "I32",
    "I64",
    "F32",
    "F64",
    "String",
    "Boolean",
    nullptr
  };
  return names;
}

inline const char *EnumNameValueType(ValueType e) {
  if (::flatbuffers::IsOutRange(e, ValueType_U8, ValueType_Boolean)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesValueType()[index];
}

struct Operation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OperationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_OPTYPE = 6,
    VT_ARGS = 8,
    VT_REVAL = 10
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  Firmoto::OperationType optype() const {
    return static_cast<Firmoto::OperationType>(GetField<int8_t>(VT_OPTYPE, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Firmoto::Value>> *args() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Firmoto::Value>> *>(VT_ARGS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Firmoto::Value>> *reval() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Firmoto::Value>> *>(VT_REVAL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int8_t>(verifier, VT_OPTYPE, 1) &&
           VerifyOffset(verifier, VT_ARGS) &&
           verifier.VerifyVector(args()) &&
           verifier.VerifyVectorOfTables(args()) &&
           VerifyOffset(verifier, VT_REVAL) &&
           verifier.VerifyVector(reval()) &&
           verifier.VerifyVectorOfTables(reval()) &&
           verifier.EndTable();
  }
};

struct OperationBuilder {
  typedef Operation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Operation::VT_NAME, name);
  }
  void add_optype(Firmoto::OperationType optype) {
    fbb_.AddElement<int8_t>(Operation::VT_OPTYPE, static_cast<int8_t>(optype), 0);
  }
  void add_args(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Firmoto::Value>>> args) {
    fbb_.AddOffset(Operation::VT_ARGS, args);
  }
  void add_reval(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Firmoto::Value>>> reval) {
    fbb_.AddOffset(Operation::VT_REVAL, reval);
  }
  explicit OperationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Operation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Operation>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Operation> CreateOperation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    Firmoto::OperationType optype = Firmoto::OperationType_GPIO,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Firmoto::Value>>> args = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Firmoto::Value>>> reval = 0) {
  OperationBuilder builder_(_fbb);
  builder_.add_reval(reval);
  builder_.add_args(args);
  builder_.add_name(name);
  builder_.add_optype(optype);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Operation> CreateOperationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    Firmoto::OperationType optype = Firmoto::OperationType_GPIO,
    const std::vector<::flatbuffers::Offset<Firmoto::Value>> *args = nullptr,
    const std::vector<::flatbuffers::Offset<Firmoto::Value>> *reval = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto args__ = args ? _fbb.CreateVector<::flatbuffers::Offset<Firmoto::Value>>(*args) : 0;
  auto reval__ = reval ? _fbb.CreateVector<::flatbuffers::Offset<Firmoto::Value>>(*reval) : 0;
  return Firmoto::CreateOperation(
      _fbb,
      name__,
      optype,
      args__,
      reval__);
}

struct Value FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ValueBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VALTYPE = 6,
    VT_VALUE = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  Firmoto::ValueType valtype() const {
    return static_cast<Firmoto::ValueType>(GetField<int8_t>(VT_VALTYPE, 0));
  }
  const ::flatbuffers::String *value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int8_t>(verifier, VT_VALTYPE, 1) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           verifier.EndTable();
  }
};

struct ValueBuilder {
  typedef Value Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Value::VT_NAME, name);
  }
  void add_valtype(Firmoto::ValueType valtype) {
    fbb_.AddElement<int8_t>(Value::VT_VALTYPE, static_cast<int8_t>(valtype), 0);
  }
  void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
    fbb_.AddOffset(Value::VT_VALUE, value);
  }
  explicit ValueBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Value> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Value>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Value> CreateValue(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    Firmoto::ValueType valtype = Firmoto::ValueType_U8,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0) {
  ValueBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_name(name);
  builder_.add_valtype(valtype);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Value> CreateValueDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    Firmoto::ValueType valtype = Firmoto::ValueType_U8,
    const char *value = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto value__ = value ? _fbb.CreateString(value) : 0;
  return Firmoto::CreateValue(
      _fbb,
      name__,
      valtype,
      value__);
}

inline const Firmoto::Operation *GetOperation(const void *buf) {
  return ::flatbuffers::GetRoot<Firmoto::Operation>(buf);
}

inline const Firmoto::Operation *GetSizePrefixedOperation(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Firmoto::Operation>(buf);
}

inline bool VerifyOperationBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Firmoto::Operation>(nullptr);
}

inline bool VerifySizePrefixedOperationBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Firmoto::Operation>(nullptr);
}

inline void FinishOperationBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Firmoto::Operation> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedOperationBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Firmoto::Operation> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Firmoto

#endif  // FLATBUFFERS_GENERATED_FIRMOTOSCHEMA_FIRMOTO_H_
