// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_FIRMOTOSCHEMA_FIRMOTO_H_
#define FLATBUFFERS_GENERATED_FIRMOTOSCHEMA_FIRMOTO_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace Firmoto {

struct Operation;
struct OperationBuilder;
struct OperationT;

struct Value;
struct ValueBuilder;
struct ValueT;

enum OperationType : int8_t {
  OperationType_GPIO = 0,
  OperationType_I2C = 1,
  OperationType_SPI = 2,
  OperationType_MIN = OperationType_GPIO,
  OperationType_MAX = OperationType_SPI
};

inline const OperationType (&EnumValuesOperationType())[3] {
  static const OperationType values[] = {
    OperationType_GPIO,
    OperationType_I2C,
    OperationType_SPI
  };
  return values;
}

inline const char * const *EnumNamesOperationType() {
  static const char * const names[4] = {
    "GPIO",
    "I2C",
    "SPI",
    nullptr
  };
  return names;
}

inline const char *EnumNameOperationType(OperationType e) {
  if (::flatbuffers::IsOutRange(e, OperationType_GPIO, OperationType_SPI)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesOperationType()[index];
}

enum SubOperationType : int8_t {
  SubOperationType_SPI_WRITE_U8 = 0,
  SubOperationType_SPI_READ_U8 = 1,
  SubOperationType_SPI_READ_U16 = 2,
  SubOperationType_SPI_READ_N = 3,
  SubOperationType_MIN = SubOperationType_SPI_WRITE_U8,
  SubOperationType_MAX = SubOperationType_SPI_READ_N
};

inline const SubOperationType (&EnumValuesSubOperationType())[4] {
  static const SubOperationType values[] = {
    SubOperationType_SPI_WRITE_U8,
    SubOperationType_SPI_READ_U8,
    SubOperationType_SPI_READ_U16,
    SubOperationType_SPI_READ_N
  };
  return values;
}

inline const char * const *EnumNamesSubOperationType() {
  static const char * const names[5] = {
    "SPI_WRITE_U8",
    "SPI_READ_U8",
    "SPI_READ_U16",
    "SPI_READ_N",
    nullptr
  };
  return names;
}

inline const char *EnumNameSubOperationType(SubOperationType e) {
  if (::flatbuffers::IsOutRange(e, SubOperationType_SPI_WRITE_U8, SubOperationType_SPI_READ_N)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSubOperationType()[index];
}

enum ValueType : int8_t {
  ValueType_U8 = 0,
  ValueType_U16 = 1,
  ValueType_U32 = 2,
  ValueType_U64 = 3,
  ValueType_I8 = 4,
  ValueType_I16 = 5,
  ValueType_I32 = 6,
  ValueType_I64 = 7,
  ValueType_F32 = 8,
  ValueType_F64 = 9,
  ValueType_String = 10,
  ValueType_Boolean = 11,
  ValueType_MIN = ValueType_U8,
  ValueType_MAX = ValueType_Boolean
};

inline const ValueType (&EnumValuesValueType())[12] {
  static const ValueType values[] = {
    ValueType_U8,
    ValueType_U16,
    ValueType_U32,
    ValueType_U64,
    ValueType_I8,
    ValueType_I16,
    ValueType_I32,
    ValueType_I64,
    ValueType_F32,
    ValueType_F64,
    ValueType_String,
    ValueType_Boolean
  };
  return values;
}

inline const char * const *EnumNamesValueType() {
  static const char * const names[13] = {
    "U8",
    "U16",
    "U32",
    "U64",
    "I8",
    "I16",
    "I32",
    "I64",
    "F32",
    "F64",
    "String",
    "Boolean",
    nullptr
  };
  return names;
}

inline const char *EnumNameValueType(ValueType e) {
  if (::flatbuffers::IsOutRange(e, ValueType_U8, ValueType_Boolean)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesValueType()[index];
}

struct OperationT : public ::flatbuffers::NativeTable {
  typedef Operation TableType;
  std::string name{};
  Firmoto::OperationType op_type = Firmoto::OperationType_GPIO;
  Firmoto::SubOperationType sub_op_type = Firmoto::SubOperationType_SPI_WRITE_U8;
  std::vector<std::unique_ptr<Firmoto::ValueT>> args{};
  std::vector<std::unique_ptr<Firmoto::ValueT>> retval{};
  OperationT() = default;
  OperationT(const OperationT &o);
  OperationT(OperationT&&) FLATBUFFERS_NOEXCEPT = default;
  OperationT &operator=(OperationT o) FLATBUFFERS_NOEXCEPT;
};

struct Operation FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OperationT NativeTableType;
  typedef OperationBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_OP_TYPE = 6,
    VT_SUB_OP_TYPE = 8,
    VT_ARGS = 10,
    VT_RETVAL = 12
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  Firmoto::OperationType op_type() const {
    return static_cast<Firmoto::OperationType>(GetField<int8_t>(VT_OP_TYPE, 0));
  }
  Firmoto::SubOperationType sub_op_type() const {
    return static_cast<Firmoto::SubOperationType>(GetField<int8_t>(VT_SUB_OP_TYPE, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Firmoto::Value>> *args() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Firmoto::Value>> *>(VT_ARGS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<Firmoto::Value>> *retval() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<Firmoto::Value>> *>(VT_RETVAL);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int8_t>(verifier, VT_OP_TYPE, 1) &&
           VerifyField<int8_t>(verifier, VT_SUB_OP_TYPE, 1) &&
           VerifyOffset(verifier, VT_ARGS) &&
           verifier.VerifyVector(args()) &&
           verifier.VerifyVectorOfTables(args()) &&
           VerifyOffset(verifier, VT_RETVAL) &&
           verifier.VerifyVector(retval()) &&
           verifier.VerifyVectorOfTables(retval()) &&
           verifier.EndTable();
  }
  OperationT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(OperationT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Operation> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const OperationT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct OperationBuilder {
  typedef Operation Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Operation::VT_NAME, name);
  }
  void add_op_type(Firmoto::OperationType op_type) {
    fbb_.AddElement<int8_t>(Operation::VT_OP_TYPE, static_cast<int8_t>(op_type), 0);
  }
  void add_sub_op_type(Firmoto::SubOperationType sub_op_type) {
    fbb_.AddElement<int8_t>(Operation::VT_SUB_OP_TYPE, static_cast<int8_t>(sub_op_type), 0);
  }
  void add_args(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Firmoto::Value>>> args) {
    fbb_.AddOffset(Operation::VT_ARGS, args);
  }
  void add_retval(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Firmoto::Value>>> retval) {
    fbb_.AddOffset(Operation::VT_RETVAL, retval);
  }
  explicit OperationBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Operation> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Operation>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Operation> CreateOperation(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    Firmoto::OperationType op_type = Firmoto::OperationType_GPIO,
    Firmoto::SubOperationType sub_op_type = Firmoto::SubOperationType_SPI_WRITE_U8,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Firmoto::Value>>> args = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<Firmoto::Value>>> retval = 0) {
  OperationBuilder builder_(_fbb);
  builder_.add_retval(retval);
  builder_.add_args(args);
  builder_.add_name(name);
  builder_.add_sub_op_type(sub_op_type);
  builder_.add_op_type(op_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Operation> CreateOperationDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    Firmoto::OperationType op_type = Firmoto::OperationType_GPIO,
    Firmoto::SubOperationType sub_op_type = Firmoto::SubOperationType_SPI_WRITE_U8,
    const std::vector<::flatbuffers::Offset<Firmoto::Value>> *args = nullptr,
    const std::vector<::flatbuffers::Offset<Firmoto::Value>> *retval = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto args__ = args ? _fbb.CreateVector<::flatbuffers::Offset<Firmoto::Value>>(*args) : 0;
  auto retval__ = retval ? _fbb.CreateVector<::flatbuffers::Offset<Firmoto::Value>>(*retval) : 0;
  return Firmoto::CreateOperation(
      _fbb,
      name__,
      op_type,
      sub_op_type,
      args__,
      retval__);
}

::flatbuffers::Offset<Operation> CreateOperation(::flatbuffers::FlatBufferBuilder &_fbb, const OperationT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct ValueT : public ::flatbuffers::NativeTable {
  typedef Value TableType;
  std::string name{};
  Firmoto::ValueType valtype = Firmoto::ValueType_U8;
  std::string value{};
};

struct Value FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ValueT NativeTableType;
  typedef ValueBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VALTYPE = 6,
    VT_VALUE = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  Firmoto::ValueType valtype() const {
    return static_cast<Firmoto::ValueType>(GetField<int8_t>(VT_VALTYPE, 0));
  }
  const ::flatbuffers::String *value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int8_t>(verifier, VT_VALTYPE, 1) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           verifier.EndTable();
  }
  ValueT *UnPack(const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(ValueT *_o, const ::flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static ::flatbuffers::Offset<Value> Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ValueT* _o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct ValueBuilder {
  typedef Value Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(Value::VT_NAME, name);
  }
  void add_valtype(Firmoto::ValueType valtype) {
    fbb_.AddElement<int8_t>(Value::VT_VALTYPE, static_cast<int8_t>(valtype), 0);
  }
  void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
    fbb_.AddOffset(Value::VT_VALUE, value);
  }
  explicit ValueBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Value> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Value>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Value> CreateValue(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    Firmoto::ValueType valtype = Firmoto::ValueType_U8,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0) {
  ValueBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_name(name);
  builder_.add_valtype(valtype);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Value> CreateValueDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    Firmoto::ValueType valtype = Firmoto::ValueType_U8,
    const char *value = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto value__ = value ? _fbb.CreateString(value) : 0;
  return Firmoto::CreateValue(
      _fbb,
      name__,
      valtype,
      value__);
}

::flatbuffers::Offset<Value> CreateValue(::flatbuffers::FlatBufferBuilder &_fbb, const ValueT *_o, const ::flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline OperationT::OperationT(const OperationT &o)
      : name(o.name),
        op_type(o.op_type),
        sub_op_type(o.sub_op_type) {
  args.reserve(o.args.size());
  for (const auto &args_ : o.args) { args.emplace_back((args_) ? new Firmoto::ValueT(*args_) : nullptr); }
  retval.reserve(o.retval.size());
  for (const auto &retval_ : o.retval) { retval.emplace_back((retval_) ? new Firmoto::ValueT(*retval_) : nullptr); }
}

inline OperationT &OperationT::operator=(OperationT o) FLATBUFFERS_NOEXCEPT {
  std::swap(name, o.name);
  std::swap(op_type, o.op_type);
  std::swap(sub_op_type, o.sub_op_type);
  std::swap(args, o.args);
  std::swap(retval, o.retval);
  return *this;
}

inline OperationT *Operation::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<OperationT>(new OperationT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Operation::UnPackTo(OperationT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = op_type(); _o->op_type = _e; }
  { auto _e = sub_op_type(); _o->sub_op_type = _e; }
  { auto _e = args(); if (_e) { _o->args.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->args[_i]) { _e->Get(_i)->UnPackTo(_o->args[_i].get(), _resolver); } else { _o->args[_i] = std::unique_ptr<Firmoto::ValueT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->args.resize(0); } }
  { auto _e = retval(); if (_e) { _o->retval.resize(_e->size()); for (::flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { if(_o->retval[_i]) { _e->Get(_i)->UnPackTo(_o->retval[_i].get(), _resolver); } else { _o->retval[_i] = std::unique_ptr<Firmoto::ValueT>(_e->Get(_i)->UnPack(_resolver)); } } } else { _o->retval.resize(0); } }
}

inline ::flatbuffers::Offset<Operation> Operation::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const OperationT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateOperation(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Operation> CreateOperation(::flatbuffers::FlatBufferBuilder &_fbb, const OperationT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const OperationT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _op_type = _o->op_type;
  auto _sub_op_type = _o->sub_op_type;
  auto _args = _o->args.size() ? _fbb.CreateVector<::flatbuffers::Offset<Firmoto::Value>> (_o->args.size(), [](size_t i, _VectorArgs *__va) { return CreateValue(*__va->__fbb, __va->__o->args[i].get(), __va->__rehasher); }, &_va ) : 0;
  auto _retval = _o->retval.size() ? _fbb.CreateVector<::flatbuffers::Offset<Firmoto::Value>> (_o->retval.size(), [](size_t i, _VectorArgs *__va) { return CreateValue(*__va->__fbb, __va->__o->retval[i].get(), __va->__rehasher); }, &_va ) : 0;
  return Firmoto::CreateOperation(
      _fbb,
      _name,
      _op_type,
      _sub_op_type,
      _args,
      _retval);
}

inline ValueT *Value::UnPack(const ::flatbuffers::resolver_function_t *_resolver) const {
  auto _o = std::unique_ptr<ValueT>(new ValueT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Value::UnPackTo(ValueT *_o, const ::flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = name(); if (_e) _o->name = _e->str(); }
  { auto _e = valtype(); _o->valtype = _e; }
  { auto _e = value(); if (_e) _o->value = _e->str(); }
}

inline ::flatbuffers::Offset<Value> Value::Pack(::flatbuffers::FlatBufferBuilder &_fbb, const ValueT* _o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  return CreateValue(_fbb, _o, _rehasher);
}

inline ::flatbuffers::Offset<Value> CreateValue(::flatbuffers::FlatBufferBuilder &_fbb, const ValueT *_o, const ::flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { ::flatbuffers::FlatBufferBuilder *__fbb; const ValueT* __o; const ::flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _name = _o->name.empty() ? 0 : _fbb.CreateString(_o->name);
  auto _valtype = _o->valtype;
  auto _value = _o->value.empty() ? 0 : _fbb.CreateString(_o->value);
  return Firmoto::CreateValue(
      _fbb,
      _name,
      _valtype,
      _value);
}

inline const Firmoto::Operation *GetOperation(const void *buf) {
  return ::flatbuffers::GetRoot<Firmoto::Operation>(buf);
}

inline const Firmoto::Operation *GetSizePrefixedOperation(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<Firmoto::Operation>(buf);
}

inline bool VerifyOperationBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<Firmoto::Operation>(nullptr);
}

inline bool VerifySizePrefixedOperationBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<Firmoto::Operation>(nullptr);
}

inline void FinishOperationBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Firmoto::Operation> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedOperationBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<Firmoto::Operation> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<Firmoto::OperationT> UnPackOperation(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<Firmoto::OperationT>(GetOperation(buf)->UnPack(res));
}

inline std::unique_ptr<Firmoto::OperationT> UnPackSizePrefixedOperation(
    const void *buf,
    const ::flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<Firmoto::OperationT>(GetSizePrefixedOperation(buf)->UnPack(res));
}

}  // namespace Firmoto

#endif  // FLATBUFFERS_GENERATED_FIRMOTOSCHEMA_FIRMOTO_H_
