# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Firmoto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Value(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Value()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsValue(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Value
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Value
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Value
    def Valtype(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Value
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ValueStart(builder):
    builder.StartObject(3)

def Start(builder):
    ValueStart(builder)

def ValueAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ValueAddName(builder, name)

def ValueAddValtype(builder, valtype):
    builder.PrependInt8Slot(1, valtype, 0)

def AddValtype(builder, valtype):
    ValueAddValtype(builder, valtype)

def ValueAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    ValueAddValue(builder, value)

def ValueEnd(builder):
    return builder.EndObject()

def End(builder):
    return ValueEnd(builder)


class ValueT(object):

    # ValueT
    def __init__(
        self,
        name = None,
        valtype = 0,
        value = None,
    ):
        self.name = name  # type: Optional[str]
        self.valtype = valtype  # type: int
        self.value = value  # type: Optional[str]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        value = Value()
        value.Init(buf, pos)
        return cls.InitFromObj(value)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, value):
        x = ValueT()
        x._UnPack(value)
        return x

    # ValueT
    def _UnPack(self, value):
        if value is None:
            return
        self.name = value.Name()
        self.valtype = value.Valtype()
        self.value = value.Value()

    # ValueT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        if self.value is not None:
            value = builder.CreateString(self.value)
        ValueStart(builder)
        if self.name is not None:
            ValueAddName(builder, name)
        ValueAddValtype(builder, self.valtype)
        if self.value is not None:
            ValueAddValue(builder, value)
        value = ValueEnd(builder)
        return value
