# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Firmoto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldU8(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldU8()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldU8(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FieldU8
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldU8
    def Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def FieldU8Start(builder):
    builder.StartObject(1)

def Start(builder):
    FieldU8Start(builder)

def FieldU8AddField(builder, field):
    builder.PrependUint8Slot(0, field, 0)

def AddField(builder, field):
    FieldU8AddField(builder, field)

def FieldU8End(builder):
    return builder.EndObject()

def End(builder):
    return FieldU8End(builder)


class FieldU8T(object):

    # FieldU8T
    def __init__(
        self,
        field = 0,
    ):
        self.field = field  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fieldU8 = FieldU8()
        fieldU8.Init(buf, pos)
        return cls.InitFromObj(fieldU8)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fieldU8):
        x = FieldU8T()
        x._UnPack(fieldU8)
        return x

    # FieldU8T
    def _UnPack(self, fieldU8):
        if fieldU8 is None:
            return
        self.field = fieldU8.Field()

    # FieldU8T
    def Pack(self, builder):
        FieldU8Start(builder)
        FieldU8AddField(builder, self.field)
        fieldU8 = FieldU8End(builder)
        return fieldU8
