# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Firmoto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldU64(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldU64()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldU64(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FieldU64
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldU64
    def Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def FieldU64Start(builder):
    builder.StartObject(1)

def Start(builder):
    FieldU64Start(builder)

def FieldU64AddField(builder, field):
    builder.PrependUint64Slot(0, field, 0)

def AddField(builder, field):
    FieldU64AddField(builder, field)

def FieldU64End(builder):
    return builder.EndObject()

def End(builder):
    return FieldU64End(builder)


class FieldU64T(object):

    # FieldU64T
    def __init__(
        self,
        field = 0,
    ):
        self.field = field  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fieldU64 = FieldU64()
        fieldU64.Init(buf, pos)
        return cls.InitFromObj(fieldU64)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fieldU64):
        x = FieldU64T()
        x._UnPack(fieldU64)
        return x

    # FieldU64T
    def _UnPack(self, fieldU64):
        if fieldU64 is None:
            return
        self.field = fieldU64.Field()

    # FieldU64T
    def Pack(self, builder):
        FieldU64Start(builder)
        FieldU64AddField(builder, self.field)
        fieldU64 = FieldU64End(builder)
        return fieldU64
