# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Firmoto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldDouble(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldDouble()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldDouble(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FieldDouble
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldDouble
    def Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def FieldDoubleStart(builder):
    builder.StartObject(1)

def Start(builder):
    FieldDoubleStart(builder)

def FieldDoubleAddField(builder, field):
    builder.PrependFloat64Slot(0, field, 0.0)

def AddField(builder, field):
    FieldDoubleAddField(builder, field)

def FieldDoubleEnd(builder):
    return builder.EndObject()

def End(builder):
    return FieldDoubleEnd(builder)


class FieldDoubleT(object):

    # FieldDoubleT
    def __init__(
        self,
        field = 0.0,
    ):
        self.field = field  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fieldDouble = FieldDouble()
        fieldDouble.Init(buf, pos)
        return cls.InitFromObj(fieldDouble)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fieldDouble):
        x = FieldDoubleT()
        x._UnPack(fieldDouble)
        return x

    # FieldDoubleT
    def _UnPack(self, fieldDouble):
        if fieldDouble is None:
            return
        self.field = fieldDouble.Field()

    # FieldDoubleT
    def Pack(self, builder):
        FieldDoubleStart(builder)
        FieldDoubleAddField(builder, self.field)
        fieldDouble = FieldDoubleEnd(builder)
        return fieldDouble
