# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Firmoto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldU32(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldU32()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldU32(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FieldU32
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldU32
    def Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def FieldU32Start(builder):
    builder.StartObject(1)

def Start(builder):
    FieldU32Start(builder)

def FieldU32AddField(builder, field):
    builder.PrependUint32Slot(0, field, 0)

def AddField(builder, field):
    FieldU32AddField(builder, field)

def FieldU32End(builder):
    return builder.EndObject()

def End(builder):
    return FieldU32End(builder)


class FieldU32T(object):

    # FieldU32T
    def __init__(
        self,
        field = 0,
    ):
        self.field = field  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fieldU32 = FieldU32()
        fieldU32.Init(buf, pos)
        return cls.InitFromObj(fieldU32)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fieldU32):
        x = FieldU32T()
        x._UnPack(fieldU32)
        return x

    # FieldU32T
    def _UnPack(self, fieldU32):
        if fieldU32 is None:
            return
        self.field = fieldU32.Field()

    # FieldU32T
    def Pack(self, builder):
        FieldU32Start(builder)
        FieldU32AddField(builder, self.field)
        fieldU32 = FieldU32End(builder)
        return fieldU32
