# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Firmoto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldI64(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldI64()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldI64(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FieldI64
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldI64
    def Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def FieldI64Start(builder):
    builder.StartObject(1)

def Start(builder):
    FieldI64Start(builder)

def FieldI64AddField(builder, field):
    builder.PrependInt64Slot(0, field, 0)

def AddField(builder, field):
    FieldI64AddField(builder, field)

def FieldI64End(builder):
    return builder.EndObject()

def End(builder):
    return FieldI64End(builder)


class FieldI64T(object):

    # FieldI64T
    def __init__(
        self,
        field = 0,
    ):
        self.field = field  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fieldI64 = FieldI64()
        fieldI64.Init(buf, pos)
        return cls.InitFromObj(fieldI64)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fieldI64):
        x = FieldI64T()
        x._UnPack(fieldI64)
        return x

    # FieldI64T
    def _UnPack(self, fieldI64):
        if fieldI64 is None:
            return
        self.field = fieldI64.Field()

    # FieldI64T
    def Pack(self, builder):
        FieldI64Start(builder)
        FieldI64AddField(builder, self.field)
        fieldI64 = FieldI64End(builder)
        return fieldI64
