# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Firmoto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldU16(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldU16()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldU16(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FieldU16
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldU16
    def Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def FieldU16Start(builder):
    builder.StartObject(1)

def Start(builder):
    FieldU16Start(builder)

def FieldU16AddField(builder, field):
    builder.PrependUint16Slot(0, field, 0)

def AddField(builder, field):
    FieldU16AddField(builder, field)

def FieldU16End(builder):
    return builder.EndObject()

def End(builder):
    return FieldU16End(builder)


class FieldU16T(object):

    # FieldU16T
    def __init__(
        self,
        field = 0,
    ):
        self.field = field  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fieldU16 = FieldU16()
        fieldU16.Init(buf, pos)
        return cls.InitFromObj(fieldU16)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fieldU16):
        x = FieldU16T()
        x._UnPack(fieldU16)
        return x

    # FieldU16T
    def _UnPack(self, fieldU16):
        if fieldU16 is None:
            return
        self.field = fieldU16.Field()

    # FieldU16T
    def Pack(self, builder):
        FieldU16Start(builder)
        FieldU16AddField(builder, self.field)
        fieldU16 = FieldU16End(builder)
        return fieldU16
