# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Firmoto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldBool(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldBool()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldBool(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FieldBool
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldBool
    def Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def FieldBoolStart(builder):
    builder.StartObject(1)

def Start(builder):
    FieldBoolStart(builder)

def FieldBoolAddField(builder, field):
    builder.PrependBoolSlot(0, field, 0)

def AddField(builder, field):
    FieldBoolAddField(builder, field)

def FieldBoolEnd(builder):
    return builder.EndObject()

def End(builder):
    return FieldBoolEnd(builder)


class FieldBoolT(object):

    # FieldBoolT
    def __init__(
        self,
        field = False,
    ):
        self.field = field  # type: bool

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fieldBool = FieldBool()
        fieldBool.Init(buf, pos)
        return cls.InitFromObj(fieldBool)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fieldBool):
        x = FieldBoolT()
        x._UnPack(fieldBool)
        return x

    # FieldBoolT
    def _UnPack(self, fieldBool):
        if fieldBool is None:
            return
        self.field = fieldBool.Field()

    # FieldBoolT
    def Pack(self, builder):
        FieldBoolStart(builder)
        FieldBoolAddField(builder, self.field)
        fieldBool = FieldBoolEnd(builder)
        return fieldBool
