# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Firmoto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldFloat(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldFloat()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldFloat(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FieldFloat
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldFloat
    def Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def FieldFloatStart(builder):
    builder.StartObject(1)

def Start(builder):
    FieldFloatStart(builder)

def FieldFloatAddField(builder, field):
    builder.PrependFloat32Slot(0, field, 0.0)

def AddField(builder, field):
    FieldFloatAddField(builder, field)

def FieldFloatEnd(builder):
    return builder.EndObject()

def End(builder):
    return FieldFloatEnd(builder)


class FieldFloatT(object):

    # FieldFloatT
    def __init__(
        self,
        field = 0.0,
    ):
        self.field = field  # type: float

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fieldFloat = FieldFloat()
        fieldFloat.Init(buf, pos)
        return cls.InitFromObj(fieldFloat)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fieldFloat):
        x = FieldFloatT()
        x._UnPack(fieldFloat)
        return x

    # FieldFloatT
    def _UnPack(self, fieldFloat):
        if fieldFloat is None:
            return
        self.field = fieldFloat.Field()

    # FieldFloatT
    def Pack(self, builder):
        FieldFloatStart(builder)
        FieldFloatAddField(builder, self.field)
        fieldFloat = FieldFloatEnd(builder)
        return fieldFloat
