# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Firmoto

class FieldType(object):
    NONE = 0
    FieldString = 1
    FieldBool = 2
    FieldI8 = 3
    FieldI16 = 4
    FieldI32 = 5
    FieldI64 = 6
    FieldU8 = 7
    FieldU16 = 8
    FieldU32 = 9
    FieldU64 = 10
    FieldFloat = 11
    FieldDouble = 12

def FieldTypeCreator(unionType, table):
    from flatbuffers.table import Table
    if not isinstance(table, Table):
        return None
    if unionType == FieldType.FieldString:
        import Firmoto.FieldString
        return Firmoto.FieldString.FieldStringT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FieldType.FieldBool:
        import Firmoto.FieldBool
        return Firmoto.FieldBool.FieldBoolT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FieldType.FieldI8:
        import Firmoto.FieldI8
        return Firmoto.FieldI8.FieldI8T.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FieldType.FieldI16:
        import Firmoto.FieldI16
        return Firmoto.FieldI16.FieldI16T.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FieldType.FieldI32:
        import Firmoto.FieldI32
        return Firmoto.FieldI32.FieldI32T.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FieldType.FieldI64:
        import Firmoto.FieldI64
        return Firmoto.FieldI64.FieldI64T.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FieldType.FieldU8:
        import Firmoto.FieldU8
        return Firmoto.FieldU8.FieldU8T.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FieldType.FieldU16:
        import Firmoto.FieldU16
        return Firmoto.FieldU16.FieldU16T.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FieldType.FieldU32:
        import Firmoto.FieldU32
        return Firmoto.FieldU32.FieldU32T.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FieldType.FieldU64:
        import Firmoto.FieldU64
        return Firmoto.FieldU64.FieldU64T.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FieldType.FieldFloat:
        import Firmoto.FieldFloat
        return Firmoto.FieldFloat.FieldFloatT.InitFromBuf(table.Bytes, table.Pos)
    if unionType == FieldType.FieldDouble:
        import Firmoto.FieldDouble
        return Firmoto.FieldDouble.FieldDoubleT.InitFromBuf(table.Bytes, table.Pos)
    return None
