# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Firmoto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class FieldI32(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = FieldI32()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsFieldI32(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # FieldI32
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # FieldI32
    def Field(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def FieldI32Start(builder):
    builder.StartObject(1)

def Start(builder):
    FieldI32Start(builder)

def FieldI32AddField(builder, field):
    builder.PrependInt32Slot(0, field, 0)

def AddField(builder, field):
    FieldI32AddField(builder, field)

def FieldI32End(builder):
    return builder.EndObject()

def End(builder):
    return FieldI32End(builder)


class FieldI32T(object):

    # FieldI32T
    def __init__(
        self,
        field = 0,
    ):
        self.field = field  # type: int

    @classmethod
    def InitFromBuf(cls, buf, pos):
        fieldI32 = FieldI32()
        fieldI32.Init(buf, pos)
        return cls.InitFromObj(fieldI32)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, fieldI32):
        x = FieldI32T()
        x._UnPack(fieldI32)
        return x

    # FieldI32T
    def _UnPack(self, fieldI32):
        if fieldI32 is None:
            return
        self.field = fieldI32.Field()

    # FieldI32T
    def Pack(self, builder):
        FieldI32Start(builder)
        FieldI32AddField(builder, self.field)
        fieldI32 = FieldI32End(builder)
        return fieldI32
