# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Firmoto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Operation(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Operation()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsOperation(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Operation
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Operation
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Operation
    def OpType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Operation
    def SubOpType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

    # Operation
    def Args(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Firmoto.Value import Value
            obj = Value()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Operation
    def ArgsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Operation
    def ArgsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Operation
    def Retval(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            from Firmoto.Value import Value
            obj = Value()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Operation
    def RetvalLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Operation
    def RetvalIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

def OperationStart(builder):
    builder.StartObject(5)

def Start(builder):
    OperationStart(builder)

def OperationAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    OperationAddName(builder, name)

def OperationAddOpType(builder, opType):
    builder.PrependInt8Slot(1, opType, 0)

def AddOpType(builder, opType):
    OperationAddOpType(builder, opType)

def OperationAddSubOpType(builder, subOpType):
    builder.PrependInt8Slot(2, subOpType, 0)

def AddSubOpType(builder, subOpType):
    OperationAddSubOpType(builder, subOpType)

def OperationAddArgs(builder, args):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(args), 0)

def AddArgs(builder, args):
    OperationAddArgs(builder, args)

def OperationStartArgsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartArgsVector(builder, numElems):
    return OperationStartArgsVector(builder, numElems)

def OperationAddRetval(builder, retval):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(retval), 0)

def AddRetval(builder, retval):
    OperationAddRetval(builder, retval)

def OperationStartRetvalVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def StartRetvalVector(builder, numElems):
    return OperationStartRetvalVector(builder, numElems)

def OperationEnd(builder):
    return builder.EndObject()

def End(builder):
    return OperationEnd(builder)

import Firmoto.Value
try:
    from typing import List
except:
    pass

class OperationT(object):

    # OperationT
    def __init__(
        self,
        name = None,
        opType = 0,
        subOpType = 0,
        args = None,
        retval = None,
    ):
        self.name = name  # type: Optional[str]
        self.opType = opType  # type: int
        self.subOpType = subOpType  # type: int
        self.args = args  # type: Optional[List[Firmoto.Value.ValueT]]
        self.retval = retval  # type: Optional[List[Firmoto.Value.ValueT]]

    @classmethod
    def InitFromBuf(cls, buf, pos):
        operation = Operation()
        operation.Init(buf, pos)
        return cls.InitFromObj(operation)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, operation):
        x = OperationT()
        x._UnPack(operation)
        return x

    # OperationT
    def _UnPack(self, operation):
        if operation is None:
            return
        self.name = operation.Name()
        self.opType = operation.OpType()
        self.subOpType = operation.SubOpType()
        if not operation.ArgsIsNone():
            self.args = []
            for i in range(operation.ArgsLength()):
                if operation.Args(i) is None:
                    self.args.append(None)
                else:
                    value_ = Firmoto.Value.ValueT.InitFromObj(operation.Args(i))
                    self.args.append(value_)
        if not operation.RetvalIsNone():
            self.retval = []
            for i in range(operation.RetvalLength()):
                if operation.Retval(i) is None:
                    self.retval.append(None)
                else:
                    value_ = Firmoto.Value.ValueT.InitFromObj(operation.Retval(i))
                    self.retval.append(value_)

    # OperationT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        if self.args is not None:
            argslist = []
            for i in range(len(self.args)):
                argslist.append(self.args[i].Pack(builder))
            OperationStartArgsVector(builder, len(self.args))
            for i in reversed(range(len(self.args))):
                builder.PrependUOffsetTRelative(argslist[i])
            args = builder.EndVector()
        if self.retval is not None:
            retvallist = []
            for i in range(len(self.retval)):
                retvallist.append(self.retval[i].Pack(builder))
            OperationStartRetvalVector(builder, len(self.retval))
            for i in reversed(range(len(self.retval))):
                builder.PrependUOffsetTRelative(retvallist[i])
            retval = builder.EndVector()
        OperationStart(builder)
        if self.name is not None:
            OperationAddName(builder, name)
        OperationAddOpType(builder, self.opType)
        OperationAddSubOpType(builder, self.subOpType)
        if self.args is not None:
            OperationAddArgs(builder, args)
        if self.retval is not None:
            OperationAddRetval(builder, retval)
        operation = OperationEnd(builder)
        return operation
