# automatically generated by the FlatBuffers compiler, do not modify

# namespace: Firmoto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Value(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Value()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsValue(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Value
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Value
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Value
    def ValueType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Value
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def ValueStart(builder):
    builder.StartObject(3)

def Start(builder):
    ValueStart(builder)

def ValueAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def AddName(builder, name):
    ValueAddName(builder, name)

def ValueAddValueType(builder, valueType):
    builder.PrependUint8Slot(1, valueType, 0)

def AddValueType(builder, valueType):
    ValueAddValueType(builder, valueType)

def ValueAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def AddValue(builder, value):
    ValueAddValue(builder, value)

def ValueEnd(builder):
    return builder.EndObject()

def End(builder):
    return ValueEnd(builder)

import Firmoto.FieldBool
import Firmoto.FieldDouble
import Firmoto.FieldFloat
import Firmoto.FieldI16
import Firmoto.FieldI32
import Firmoto.FieldI64
import Firmoto.FieldI8
import Firmoto.FieldString
import Firmoto.FieldType
import Firmoto.FieldU16
import Firmoto.FieldU32
import Firmoto.FieldU64
import Firmoto.FieldU8
try:
    from typing import Union
except:
    pass

class ValueT(object):

    # ValueT
    def __init__(
        self,
        name = None,
        valueType = 0,
        value = None,
    ):
        self.name = name  # type: Optional[str]
        self.valueType = valueType  # type: int
        self.value = value  # type: Union[None, 'Firmoto.FieldString.FieldStringT', 'Firmoto.FieldBool.FieldBoolT', 'Firmoto.FieldI8.FieldI8T', 'Firmoto.FieldI16.FieldI16T', 'Firmoto.FieldI32.FieldI32T', 'Firmoto.FieldI64.FieldI64T', 'Firmoto.FieldU8.FieldU8T', 'Firmoto.FieldU16.FieldU16T', 'Firmoto.FieldU32.FieldU32T', 'Firmoto.FieldU64.FieldU64T', 'Firmoto.FieldFloat.FieldFloatT', 'Firmoto.FieldDouble.FieldDoubleT']

    @classmethod
    def InitFromBuf(cls, buf, pos):
        value = Value()
        value.Init(buf, pos)
        return cls.InitFromObj(value)

    @classmethod
    def InitFromPackedBuf(cls, buf, pos=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, pos)
        return cls.InitFromBuf(buf, pos+n)

    @classmethod
    def InitFromObj(cls, value):
        x = ValueT()
        x._UnPack(value)
        return x

    # ValueT
    def _UnPack(self, value):
        if value is None:
            return
        self.name = value.Name()
        self.valueType = value.ValueType()
        self.value = Firmoto.FieldType.FieldTypeCreator(self.valueType, value.Value())

    # ValueT
    def Pack(self, builder):
        if self.name is not None:
            name = builder.CreateString(self.name)
        if self.value is not None:
            value = self.value.Pack(builder)
        ValueStart(builder)
        if self.name is not None:
            ValueAddName(builder, name)
        ValueAddValueType(builder, self.valueType)
        if self.value is not None:
            ValueAddValue(builder, value)
        value = ValueEnd(builder)
        return value
