// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { OperationType } from '../firmoto/operation-type.js';
import { SubOperationType } from '../firmoto/sub-operation-type.js';
import { Value } from '../firmoto/value.js';


export class Operation {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Operation {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsOperation(bb:flatbuffers.ByteBuffer, obj?:Operation):Operation {
  return (obj || new Operation()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsOperation(bb:flatbuffers.ByteBuffer, obj?:Operation):Operation {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Operation()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

name():string|null
name(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
name(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

opType():OperationType {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : OperationType.GPIO;
}

subOpType():SubOperationType {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : SubOperationType.SPI_WRITE_U8;
}

args(index: number, obj?:Value):Value|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Value()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

argsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

retval(index: number, obj?:Value):Value|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Value()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

retvalLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startOperation(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addName(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, nameOffset, 0);
}

static addOpType(builder:flatbuffers.Builder, opType:OperationType) {
  builder.addFieldInt8(1, opType, OperationType.GPIO);
}

static addSubOpType(builder:flatbuffers.Builder, subOpType:SubOperationType) {
  builder.addFieldInt8(2, subOpType, SubOperationType.SPI_WRITE_U8);
}

static addArgs(builder:flatbuffers.Builder, argsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(3, argsOffset, 0);
}

static createArgsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startArgsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRetval(builder:flatbuffers.Builder, retvalOffset:flatbuffers.Offset) {
  builder.addFieldOffset(4, retvalOffset, 0);
}

static createRetvalVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRetvalVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endOperation(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishOperationBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedOperationBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createOperation(builder:flatbuffers.Builder, nameOffset:flatbuffers.Offset, opType:OperationType, subOpType:SubOperationType, argsOffset:flatbuffers.Offset, retvalOffset:flatbuffers.Offset):flatbuffers.Offset {
  Operation.startOperation(builder);
  Operation.addName(builder, nameOffset);
  Operation.addOpType(builder, opType);
  Operation.addSubOpType(builder, subOpType);
  Operation.addArgs(builder, argsOffset);
  Operation.addRetval(builder, retvalOffset);
  return Operation.endOperation(builder);
}
}
