// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Firmoto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FieldI16T struct {
	Field int16 `json:"field"`
}

func (t *FieldI16T) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	FieldI16Start(builder)
	FieldI16AddField(builder, t.Field)
	return FieldI16End(builder)
}

func (rcv *FieldI16) UnPackTo(t *FieldI16T) {
	t.Field = rcv.Field()
}

func (rcv *FieldI16) UnPack() *FieldI16T {
	if rcv == nil {
		return nil
	}
	t := &FieldI16T{}
	rcv.UnPackTo(t)
	return t
}

type FieldI16 struct {
	_tab flatbuffers.Table
}

func GetRootAsFieldI16(buf []byte, offset flatbuffers.UOffsetT) *FieldI16 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FieldI16{}
	x.Init(buf, n+offset)
	return x
}

func FinishFieldI16Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFieldI16(buf []byte, offset flatbuffers.UOffsetT) *FieldI16 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FieldI16{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFieldI16Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FieldI16) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FieldI16) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FieldI16) Field() int16 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt16(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FieldI16) MutateField(n int16) bool {
	return rcv._tab.MutateInt16Slot(4, n)
}

func FieldI16Start(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FieldI16AddField(builder *flatbuffers.Builder, field int16) {
	builder.PrependInt16Slot(0, field, 0)
}
func FieldI16End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
