// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Firmoto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FieldI64T struct {
	Field int64 `json:"field"`
}

func (t *FieldI64T) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	FieldI64Start(builder)
	FieldI64AddField(builder, t.Field)
	return FieldI64End(builder)
}

func (rcv *FieldI64) UnPackTo(t *FieldI64T) {
	t.Field = rcv.Field()
}

func (rcv *FieldI64) UnPack() *FieldI64T {
	if rcv == nil {
		return nil
	}
	t := &FieldI64T{}
	rcv.UnPackTo(t)
	return t
}

type FieldI64 struct {
	_tab flatbuffers.Table
}

func GetRootAsFieldI64(buf []byte, offset flatbuffers.UOffsetT) *FieldI64 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FieldI64{}
	x.Init(buf, n+offset)
	return x
}

func FinishFieldI64Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFieldI64(buf []byte, offset flatbuffers.UOffsetT) *FieldI64 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FieldI64{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFieldI64Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FieldI64) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FieldI64) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FieldI64) Field() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FieldI64) MutateField(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func FieldI64Start(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FieldI64AddField(builder *flatbuffers.Builder, field int64) {
	builder.PrependInt64Slot(0, field, 0)
}
func FieldI64End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
