// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Firmoto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FieldStringT struct {
	Field string `json:"field"`
}

func (t *FieldStringT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	fieldOffset := flatbuffers.UOffsetT(0)
	if t.Field != "" {
		fieldOffset = builder.CreateString(t.Field)
	}
	FieldStringStart(builder)
	FieldStringAddField(builder, fieldOffset)
	return FieldStringEnd(builder)
}

func (rcv *FieldString) UnPackTo(t *FieldStringT) {
	t.Field = string(rcv.Field())
}

func (rcv *FieldString) UnPack() *FieldStringT {
	if rcv == nil {
		return nil
	}
	t := &FieldStringT{}
	rcv.UnPackTo(t)
	return t
}

type FieldString struct {
	_tab flatbuffers.Table
}

func GetRootAsFieldString(buf []byte, offset flatbuffers.UOffsetT) *FieldString {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FieldString{}
	x.Init(buf, n+offset)
	return x
}

func FinishFieldStringBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFieldString(buf []byte, offset flatbuffers.UOffsetT) *FieldString {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FieldString{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFieldStringBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FieldString) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FieldString) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FieldString) Field() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func FieldStringStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FieldStringAddField(builder *flatbuffers.Builder, field flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(field), 0)
}
func FieldStringEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
