// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Firmoto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FieldDoubleT struct {
	Field float64 `json:"field"`
}

func (t *FieldDoubleT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	FieldDoubleStart(builder)
	FieldDoubleAddField(builder, t.Field)
	return FieldDoubleEnd(builder)
}

func (rcv *FieldDouble) UnPackTo(t *FieldDoubleT) {
	t.Field = rcv.Field()
}

func (rcv *FieldDouble) UnPack() *FieldDoubleT {
	if rcv == nil {
		return nil
	}
	t := &FieldDoubleT{}
	rcv.UnPackTo(t)
	return t
}

type FieldDouble struct {
	_tab flatbuffers.Table
}

func GetRootAsFieldDouble(buf []byte, offset flatbuffers.UOffsetT) *FieldDouble {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FieldDouble{}
	x.Init(buf, n+offset)
	return x
}

func FinishFieldDoubleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFieldDouble(buf []byte, offset flatbuffers.UOffsetT) *FieldDouble {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FieldDouble{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFieldDoubleBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FieldDouble) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FieldDouble) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FieldDouble) Field() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *FieldDouble) MutateField(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func FieldDoubleStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FieldDoubleAddField(builder *flatbuffers.Builder, field float64) {
	builder.PrependFloat64Slot(0, field, 0.0)
}
func FieldDoubleEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
