// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Firmoto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FieldU64T struct {
	Field uint64 `json:"field"`
}

func (t *FieldU64T) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	FieldU64Start(builder)
	FieldU64AddField(builder, t.Field)
	return FieldU64End(builder)
}

func (rcv *FieldU64) UnPackTo(t *FieldU64T) {
	t.Field = rcv.Field()
}

func (rcv *FieldU64) UnPack() *FieldU64T {
	if rcv == nil {
		return nil
	}
	t := &FieldU64T{}
	rcv.UnPackTo(t)
	return t
}

type FieldU64 struct {
	_tab flatbuffers.Table
}

func GetRootAsFieldU64(buf []byte, offset flatbuffers.UOffsetT) *FieldU64 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FieldU64{}
	x.Init(buf, n+offset)
	return x
}

func FinishFieldU64Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFieldU64(buf []byte, offset flatbuffers.UOffsetT) *FieldU64 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FieldU64{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFieldU64Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FieldU64) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FieldU64) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FieldU64) Field() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FieldU64) MutateField(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func FieldU64Start(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FieldU64AddField(builder *flatbuffers.Builder, field uint64) {
	builder.PrependUint64Slot(0, field, 0)
}
func FieldU64End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
