// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Firmoto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FieldBoolT struct {
	Field bool `json:"field"`
}

func (t *FieldBoolT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	FieldBoolStart(builder)
	FieldBoolAddField(builder, t.Field)
	return FieldBoolEnd(builder)
}

func (rcv *FieldBool) UnPackTo(t *FieldBoolT) {
	t.Field = rcv.Field()
}

func (rcv *FieldBool) UnPack() *FieldBoolT {
	if rcv == nil {
		return nil
	}
	t := &FieldBoolT{}
	rcv.UnPackTo(t)
	return t
}

type FieldBool struct {
	_tab flatbuffers.Table
}

func GetRootAsFieldBool(buf []byte, offset flatbuffers.UOffsetT) *FieldBool {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FieldBool{}
	x.Init(buf, n+offset)
	return x
}

func FinishFieldBoolBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFieldBool(buf []byte, offset flatbuffers.UOffsetT) *FieldBool {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FieldBool{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFieldBoolBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FieldBool) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FieldBool) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FieldBool) Field() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *FieldBool) MutateField(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func FieldBoolStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FieldBoolAddField(builder *flatbuffers.Builder, field bool) {
	builder.PrependBoolSlot(0, field, false)
}
func FieldBoolEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
