// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Firmoto

import (
	flatbuffers "github.com/google/flatbuffers/go"
	"strconv"
)

type FieldType byte

const (
	FieldTypeNONE        FieldType = 0
	FieldTypeFieldString FieldType = 1
	FieldTypeFieldBool   FieldType = 2
	FieldTypeFieldI8     FieldType = 3
	FieldTypeFieldI16    FieldType = 4
	FieldTypeFieldI32    FieldType = 5
	FieldTypeFieldI64    FieldType = 6
	FieldTypeFieldU8     FieldType = 7
	FieldTypeFieldU16    FieldType = 8
	FieldTypeFieldU32    FieldType = 9
	FieldTypeFieldU64    FieldType = 10
	FieldTypeFieldFloat  FieldType = 11
	FieldTypeFieldDouble FieldType = 12
)

var EnumNamesFieldType = map[FieldType]string{
	FieldTypeNONE:        "NONE",
	FieldTypeFieldString: "FieldString",
	FieldTypeFieldBool:   "FieldBool",
	FieldTypeFieldI8:     "FieldI8",
	FieldTypeFieldI16:    "FieldI16",
	FieldTypeFieldI32:    "FieldI32",
	FieldTypeFieldI64:    "FieldI64",
	FieldTypeFieldU8:     "FieldU8",
	FieldTypeFieldU16:    "FieldU16",
	FieldTypeFieldU32:    "FieldU32",
	FieldTypeFieldU64:    "FieldU64",
	FieldTypeFieldFloat:  "FieldFloat",
	FieldTypeFieldDouble: "FieldDouble",
}

var EnumValuesFieldType = map[string]FieldType{
	"NONE":        FieldTypeNONE,
	"FieldString": FieldTypeFieldString,
	"FieldBool":   FieldTypeFieldBool,
	"FieldI8":     FieldTypeFieldI8,
	"FieldI16":    FieldTypeFieldI16,
	"FieldI32":    FieldTypeFieldI32,
	"FieldI64":    FieldTypeFieldI64,
	"FieldU8":     FieldTypeFieldU8,
	"FieldU16":    FieldTypeFieldU16,
	"FieldU32":    FieldTypeFieldU32,
	"FieldU64":    FieldTypeFieldU64,
	"FieldFloat":  FieldTypeFieldFloat,
	"FieldDouble": FieldTypeFieldDouble,
}

func (v FieldType) String() string {
	if s, ok := EnumNamesFieldType[v]; ok {
		return s
	}
	return "FieldType(" + strconv.FormatInt(int64(v), 10) + ")"
}

type FieldTypeT struct {
	Type FieldType
	Value interface{}
}

func (t *FieldTypeT) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	switch t.Type {
	case FieldTypeFieldString:
		return t.Value.(*FieldStringT).Pack(builder)
	case FieldTypeFieldBool:
		return t.Value.(*FieldBoolT).Pack(builder)
	case FieldTypeFieldI8:
		return t.Value.(*FieldI8T).Pack(builder)
	case FieldTypeFieldI16:
		return t.Value.(*FieldI16T).Pack(builder)
	case FieldTypeFieldI32:
		return t.Value.(*FieldI32T).Pack(builder)
	case FieldTypeFieldI64:
		return t.Value.(*FieldI64T).Pack(builder)
	case FieldTypeFieldU8:
		return t.Value.(*FieldU8T).Pack(builder)
	case FieldTypeFieldU16:
		return t.Value.(*FieldU16T).Pack(builder)
	case FieldTypeFieldU32:
		return t.Value.(*FieldU32T).Pack(builder)
	case FieldTypeFieldU64:
		return t.Value.(*FieldU64T).Pack(builder)
	case FieldTypeFieldFloat:
		return t.Value.(*FieldFloatT).Pack(builder)
	case FieldTypeFieldDouble:
		return t.Value.(*FieldDoubleT).Pack(builder)
	}
	return 0
}

func (rcv FieldType) UnPack(table flatbuffers.Table) *FieldTypeT {
	switch rcv {
	case FieldTypeFieldString:
		var x FieldString
		x.Init(table.Bytes, table.Pos)
		return &FieldTypeT{Type: FieldTypeFieldString, Value: x.UnPack()}
	case FieldTypeFieldBool:
		var x FieldBool
		x.Init(table.Bytes, table.Pos)
		return &FieldTypeT{Type: FieldTypeFieldBool, Value: x.UnPack()}
	case FieldTypeFieldI8:
		var x FieldI8
		x.Init(table.Bytes, table.Pos)
		return &FieldTypeT{Type: FieldTypeFieldI8, Value: x.UnPack()}
	case FieldTypeFieldI16:
		var x FieldI16
		x.Init(table.Bytes, table.Pos)
		return &FieldTypeT{Type: FieldTypeFieldI16, Value: x.UnPack()}
	case FieldTypeFieldI32:
		var x FieldI32
		x.Init(table.Bytes, table.Pos)
		return &FieldTypeT{Type: FieldTypeFieldI32, Value: x.UnPack()}
	case FieldTypeFieldI64:
		var x FieldI64
		x.Init(table.Bytes, table.Pos)
		return &FieldTypeT{Type: FieldTypeFieldI64, Value: x.UnPack()}
	case FieldTypeFieldU8:
		var x FieldU8
		x.Init(table.Bytes, table.Pos)
		return &FieldTypeT{Type: FieldTypeFieldU8, Value: x.UnPack()}
	case FieldTypeFieldU16:
		var x FieldU16
		x.Init(table.Bytes, table.Pos)
		return &FieldTypeT{Type: FieldTypeFieldU16, Value: x.UnPack()}
	case FieldTypeFieldU32:
		var x FieldU32
		x.Init(table.Bytes, table.Pos)
		return &FieldTypeT{Type: FieldTypeFieldU32, Value: x.UnPack()}
	case FieldTypeFieldU64:
		var x FieldU64
		x.Init(table.Bytes, table.Pos)
		return &FieldTypeT{Type: FieldTypeFieldU64, Value: x.UnPack()}
	case FieldTypeFieldFloat:
		var x FieldFloat
		x.Init(table.Bytes, table.Pos)
		return &FieldTypeT{Type: FieldTypeFieldFloat, Value: x.UnPack()}
	case FieldTypeFieldDouble:
		var x FieldDouble
		x.Init(table.Bytes, table.Pos)
		return &FieldTypeT{Type: FieldTypeFieldDouble, Value: x.UnPack()}
	}
	return nil
}
