// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Firmoto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FieldI32T struct {
	Field int32 `json:"field"`
}

func (t *FieldI32T) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	FieldI32Start(builder)
	FieldI32AddField(builder, t.Field)
	return FieldI32End(builder)
}

func (rcv *FieldI32) UnPackTo(t *FieldI32T) {
	t.Field = rcv.Field()
}

func (rcv *FieldI32) UnPack() *FieldI32T {
	if rcv == nil {
		return nil
	}
	t := &FieldI32T{}
	rcv.UnPackTo(t)
	return t
}

type FieldI32 struct {
	_tab flatbuffers.Table
}

func GetRootAsFieldI32(buf []byte, offset flatbuffers.UOffsetT) *FieldI32 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FieldI32{}
	x.Init(buf, n+offset)
	return x
}

func FinishFieldI32Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFieldI32(buf []byte, offset flatbuffers.UOffsetT) *FieldI32 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FieldI32{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFieldI32Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FieldI32) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FieldI32) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FieldI32) Field() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FieldI32) MutateField(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func FieldI32Start(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FieldI32AddField(builder *flatbuffers.Builder, field int32) {
	builder.PrependInt32Slot(0, field, 0)
}
func FieldI32End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
