// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package Firmoto

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type FieldU8T struct {
	Field byte `json:"field"`
}

func (t *FieldU8T) Pack(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	if t == nil {
		return 0
	}
	FieldU8Start(builder)
	FieldU8AddField(builder, t.Field)
	return FieldU8End(builder)
}

func (rcv *FieldU8) UnPackTo(t *FieldU8T) {
	t.Field = rcv.Field()
}

func (rcv *FieldU8) UnPack() *FieldU8T {
	if rcv == nil {
		return nil
	}
	t := &FieldU8T{}
	rcv.UnPackTo(t)
	return t
}

type FieldU8 struct {
	_tab flatbuffers.Table
}

func GetRootAsFieldU8(buf []byte, offset flatbuffers.UOffsetT) *FieldU8 {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &FieldU8{}
	x.Init(buf, n+offset)
	return x
}

func FinishFieldU8Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsFieldU8(buf []byte, offset flatbuffers.UOffsetT) *FieldU8 {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &FieldU8{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedFieldU8Buffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *FieldU8) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *FieldU8) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *FieldU8) Field() byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetByte(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *FieldU8) MutateField(n byte) bool {
	return rcv._tab.MutateByteSlot(4, n)
}

func FieldU8Start(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func FieldU8AddField(builder *flatbuffers.Builder, field byte) {
	builder.PrependByteSlot(0, field, 0)
}
func FieldU8End(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
