# reference: https://docs.rust-embedded.org/book/start/qemu.html
default: l

l: 
  cargo run --bin

b: 
  RUSTFLAGS="-Awarnings" cargo build

r binName :  
  just b
  qemu-system-arm \
    -cpu cortex-m4 \
    -machine olimex-stm32-h405 \
    -nographic \
    -semihosting-config enable=on,target=native \
    -kernel ./target/thumbv7em-none-eabi/debug/{{binName}}

